# Generated by Django 5.2.13 on 2026-05-30 11:47

import amuse_bouche.models
import django.db.models.deletion
import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0016_article_category'),
        ('recipes', '0034_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmuseBouche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('media_folder', models.CharField(blank=True, db_index=True, editable=False, max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('mini_recipe', 'Mini Recipe'), ('snack', 'Snack'), ('sauce', 'Sauce'), ('cocktail', 'Cocktail'), ('quick_tip', 'Quick Tip'), ('plating_idea', 'Plating Idea'), ('leftover_idea', 'Leftover Idea'), ('irish_bite', 'Irish Bite'), ('chef_trick', 'Chef Trick'), ('behind_the_dish', 'Behind The Dish')], db_index=True, default='irish_bite', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('NEEDS_CHANGES', 'Needs changes'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=amuse_bouche.models.amuse_bouche_cover_upload_to, validators=[recipes.validators.ImageUploadValidator()])),
                ('cover_image_alt', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('allow_comments', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('moderation_note', models.TextField(blank=True, default='')),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amuse_bouche_items', to='recipes.recipeauthor')),
                ('linked_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amuse_bouche_items', to='articles.article')),
                ('linked_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amuse_bouche_items', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Amuse-Bouche',
                'verbose_name_plural': 'Amuse-Bouche',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmuseBoucheGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=amuse_bouche.models.amuse_bouche_gallery_upload_to, validators=[recipes.validators.ImageUploadValidator()])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amuse_bouche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='amuse_bouche.amusebouche')),
            ],
            options={
                'verbose_name': 'Amuse-Bouche gallery image',
                'verbose_name_plural': 'Amuse-Bouche gallery images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='amusebouche',
            index=models.Index(fields=['status', '-published_at'], name='amuse_bouch_status_2e8721_idx'),
        ),
        migrations.AddIndex(
            model_name='amusebouche',
            index=models.Index(fields=['content_type', 'status'], name='amuse_bouch_content_20afc5_idx'),
        ),
        migrations.AddIndex(
            model_name='amusebouche',
            index=models.Index(fields=['is_featured', 'status'], name='amuse_bouch_is_feat_5814b0_idx'),
        ),
    ]
