# Generated by Django 5.2.13 on 2026-06-01 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuse_bouche', '0002_moderation_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amusebouche',
            name='emoji_description',
            field=models.TextField(blank=True, help_text='Auto-generated emoji-decorated description (via Anthropic API). Edit freely.'),
        ),
        migrations.CreateModel(
            name='AmuseBoucheComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amuse_bouche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='amuse_bouche.amusebouche')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amuse-Bouche comment',
                'verbose_name_plural': 'Amuse-Bouche comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['amuse_bouche', 'is_deleted', 'created_at'], name='amuse_bouch_amuse_b_61b343_idx')],
            },
        ),
    ]
