# Generated by Django 5.2 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amuse_bouche", "0003_amusebouche_emoji_description_amusebouchecomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amusebouche",
            name="emoji_description",
            field=models.TextField(
                blank=True,
                help_text="Emoji-decorated description shown in the feed card. Generate via admin action or management command; edit freely.",
            ),
        ),
    ]
