# Generated by Django 5.2.13 on 2026-06-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuse_bouche', '0009_add_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='amusebouche',
            name='is_announcement',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
