# Generated by Django 5.2.13 on 2026-06-19 10:46

import django.db.models.deletion
import pinch.models
import recipes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0017_alter_article_source_type'),
        ('recipes', '0035_recipeauthor_can_generate_ai_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('media_folder', models.CharField(blank=True, db_index=True, editable=False, max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('mini_recipe', 'Mini Recipe'), ('snack', 'Snack'), ('sauce', 'Sauce'), ('cocktail', 'Cocktail'), ('quick_tip', 'Quick Tip'), ('plating_idea', 'Plating Idea'), ('leftover_idea', 'Leftover Idea'), ('irish_bite', 'Irish Bite'), ('chef_trick', 'Chef Trick'), ('behind_the_dish', 'Behind The Dish')], db_index=True, default='irish_bite', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('NEEDS_CHANGES', 'Needs changes'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=pinch.models.pinch_cover_upload_to, validators=[recipes.validators.ImageUploadValidator()])),
                ('cover_image_alt', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_announcement', models.BooleanField(db_index=True, default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('moderation_note', models.TextField(blank=True, default='')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('image_rights_status', models.CharField(choices=[('own', 'My own photo'), ('ai_generated', 'AI generated image'), ('licensed', 'Licensed (CC, stock, written permission)'), ('public_domain', 'Public domain'), ('not_applicable', 'No image uploaded')], default='not_applicable', max_length=20, verbose_name='Image rights')),
                ('image_rights_note', models.CharField(blank=True, help_text='Credit line or permission reference if applicable.', max_length=255, verbose_name='Image rights note')),
                ('source_type', models.CharField(choices=[('original', 'Original'), ('ai_assisted', 'AI assisted'), ('family', 'Family recipe'), ('cookbook', 'Cookbook'), ('website', 'Website'), ('restaurant', 'Restaurant'), ('other', 'Other')], default='original', max_length=20, verbose_name='Source type')),
                ('source_title', models.CharField(blank=True, max_length=255, verbose_name='Source title')),
                ('source_author', models.CharField(blank=True, max_length=255, verbose_name='Source author')),
                ('source_url', models.URLField(blank=True, verbose_name='Source URL')),
                ('source_note', models.TextField(blank=True, verbose_name='Source note')),
                ('confirmed_own_work', models.BooleanField(default=False, verbose_name='Confirmed: original or properly credited work')),
                ('confirmed_image_rights', models.BooleanField(default=False, verbose_name='Confirmed: image rights')),
                ('confirmed_rules', models.BooleanField(default=False, verbose_name='Confirmed: content publishing rules')),
                ('confirmation_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed at')),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=255)),
                ('emoji_description', models.TextField(blank=True, help_text='Emoji-decorated description shown in the feed card. Generate via admin action or management command; edit freely.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pinch_items', to='recipes.recipeauthor')),
                ('confirmed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_amuse_bouche_items', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed by')),
                ('linked_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinch_items', to='articles.article')),
                ('linked_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinch_items', to='recipes.recipe')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_amuse_bouche_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinch',
                'verbose_name_plural': 'Pinch',
                'db_table': 'amuse_bouche_amusebouche',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinchComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amuse_bouche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pinch.pinch')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='pinch.pinchcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinch comment',
                'verbose_name_plural': 'Pinch comments',
                'db_table': 'amuse_bouche_amusebouchecomment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinchGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pinch.models.pinch_gallery_upload_to, validators=[recipes.validators.ImageUploadValidator()])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amuse_bouche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pinch.pinch')),
            ],
            options={
                'verbose_name': 'Pinch gallery image',
                'verbose_name_plural': 'Pinch gallery images',
                'db_table': 'amuse_bouche_amusebouchegalleryimage',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pinch',
            index=models.Index(fields=['status', '-published_at'], name='amuse_bouch_status_2e8721_idx'),
        ),
        migrations.AddIndex(
            model_name='pinch',
            index=models.Index(fields=['content_type', 'status'], name='amuse_bouch_content_20afc5_idx'),
        ),
        migrations.AddIndex(
            model_name='pinch',
            index=models.Index(fields=['is_featured', 'status'], name='amuse_bouch_is_feat_5814b0_idx'),
        ),
        migrations.AddIndex(
            model_name='pinchcomment',
            index=models.Index(fields=['amuse_bouche', 'is_deleted', 'created_at'], name='amuse_bouch_amuse_b_61b343_idx'),
        ),
    ]
