# Generated by Django 5.2.13 on 2026-06-29 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinch', '0003_cleanup_legacy_content_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pinch',
            new_name='pinch_pinch_status_646951_idx',
            old_name='amuse_bouch_status_2e8721_idx',
        ),
        migrations.RenameIndex(
            model_name='pinch',
            new_name='pinch_pinch_content_e91097_idx',
            old_name='amuse_bouch_content_20afc5_idx',
        ),
        migrations.RenameIndex(
            model_name='pinch',
            new_name='pinch_pinch_is_feat_4cede0_idx',
            old_name='amuse_bouch_is_feat_5814b0_idx',
        ),
        migrations.AlterField(
            model_name='pinch',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_pinch_items', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed by'),
        ),
        migrations.AlterField(
            model_name='pinch',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_pinch_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pinchcomment',
            index=models.Index(fields=['pinch', 'is_deleted', 'created_at'], name='pinch_pinch_pinch_i_a42d52_idx'),
        ),
    ]
