# Generated by Django 5.2.8 on 2026-04-10 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0001_initial'),
        ('recipes', '0003_remove_recipe_media_uid_recipe_media_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='articles', to='recipes.recipe', verbose_name='Related recipe'),
        ),
    ]
