# Generated by Django 5.2.8 on 2026-04-10

from django.db import migrations, models

import articles.models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_article_related_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="media_folder",
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="article",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=articles.models.article_cover_upload_to,
                verbose_name="Preview image",
            ),
        ),
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to=articles.models.article_gallery_upload_to)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article gallery image",
                "verbose_name_plural": "Article gallery images",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
