# Generated by Django 5.2.13 on 2026-05-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_legal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_rights_status',
            field=models.CharField(choices=[('own', 'My own photo'), ('ai_generated', 'AI generated image'), ('licensed', 'Licensed (CC, stock, written permission)'), ('public_domain', 'Public domain'), ('not_applicable', 'No image uploaded')], default='own', max_length=20, verbose_name='Image rights'),
        ),
    ]
