# Generated by Django 5.2.13 on 2026-05-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_moderation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hero_image_alt_text',
            field=models.CharField(blank=True, help_text='Describe the article image for accessibility and search indexing.', max_length=255, verbose_name='Article image alt text'),
        ),
    ]
