# Generated by Django 5.2.13 on 2026-05-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_hero_image_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('NEEDS_CHANGES', 'Needs changes'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
