# Generated by Django 5.2.13 on 2026-05-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('baking', 'Baking'), ('soups_and_stews', 'Soups and Stews'), ('seafood', 'Seafood'), ('fish', 'Fish'), ('potatoes', 'Potatoes'), ('dairy_products', 'Dairy Products'), ('vegetables', 'Vegetables'), ('meat', 'Meat'), ('poultry_and_game', 'Poultry and Game'), ('desserts_and_drinks', 'Desserts and Drinks')], db_index=True, default='baking', max_length=40, verbose_name='Category'),
        ),
    ]
