# Generated by Django 5.2 on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0016_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("original", "Original writing"),
                    ("adapted", "Adapted from a source"),
                    ("inspired", "Inspired by a source"),
                    ("ai_assisted", "AI-assisted content"),
                    ("human_reviewed_ai", "Human-reviewed AI-assisted content"),
                ],
                default="original",
                max_length=20,
            ),
        ),
    ]
