# Generated by Django 5.2.13 on 2026-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_article_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('baking', 'Baking'), ('soups_and_stews', 'Soups and Stews'), ('seafood', 'Seafood'), ('fish', 'Fish'), ('potatoes', 'Potatoes'), ('dairy_products', 'Dairy Products'), ('vegetables', 'Vegetables'), ('meat', 'Meat'), ('poultry_and_game', 'Poultry and Game'), ('desserts_and_drinks', 'Desserts and Drinks'), ('beyond_the_kitchen', 'Beyond the Kitchen'), ('culinary_tech_innovations', 'Culinary Tech & Innovations')], db_index=True, default='baking', max_length=40, verbose_name='Category'),
        ),
    ]
