# Generated by Django 5.2.8 on 2026-04-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0004_article_author_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(verbose_name='Published'),
        ),
    ]
