# Generated by Django 5.2.13 on 2026-04-29 13:45

from django.db import migrations, models

import articles.models
import recipes.validators


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0005_alter_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.article_cover_upload_to,
                                    validators=[recipes.validators.ImageUploadValidator()],
                                    verbose_name='Preview image'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to=articles.models.article_gallery_upload_to,
                                    validators=[recipes.validators.ImageUploadValidator()]),
        ),
    ]
