from django.urls import path

from . import views

app_name = "chef_battle"

urlpatterns = [
    path("", views.battle_home, name="home"),
    path("arena/", views.arena, name="arena"),
    path("arena/battle-popup/", views.arena_battle_popup, name="arena_battle_popup"),
    path("arena/ping/", views.arena_ping, name="arena_ping"),
    path("arena/state/", views.arena_state, name="arena_state"),
    path("arena/blast/", views.arena_blast, name="arena_blast"),
    path("guide/", views.battle_guide, name="guide"),
    path("rules/", views.battle_rules, name="rules"),
    path("enroll/", views.chef_enroll, name="chef_enroll"),
    path("enroll/success/", views.enroll_success, name="enroll_success"),
    path("age-verification/", views.age_verification, name="age_verification"),
    path("tokens/", views.token_shop, name="token_shop"),
    path("tokens/checkout/", views.token_checkout_create, name="token_checkout_create"),
    path("tokens/checkout/success/", views.token_checkout_success, name="token_checkout_success"),
    path("tokens/checkout/cancel/", views.token_checkout_cancel, name="token_checkout_cancel"),
    path("stripe/webhook/", views.token_stripe_webhook, name="token_stripe_webhook"),
    path("season/", views.season_leaderboard, name="season_leaderboard"),
    path("roadmap/", views.battlefield_progress, name="battlefield_progress"),
    path("rankings/", views.rankings, name="rankings"),
    path("challenges/", views.challenge_list, name="challenge_list"),
    path("challenges/create/", views.challenge_create, name="challenge_create"),
    path("challenges/<int:pk>/respond/", views.challenge_respond, name="challenge_respond"),
    path("battles/<int:pk>/", views.battle_detail, name="battle_detail"),
    path("battles/<int:pk>/submit/", views.battle_entry_submit, name="battle_entry_submit"),
    path("battles/<int:pk>/vote/", views.battle_vote, name="battle_vote"),
    path("my-moves/", views.my_moves, name="my_moves"),
    path("poll/", views.notifications_poll, name="notifications_poll"),
    path("notifications/", views.notifications_inbox, name="notifications_inbox"),
    path("battles/<int:pk>/combat/", views.battle_combat_action, name="battle_combat_action"),
    path("battles/<int:pk>/state/", views.battle_state_poll, name="battle_state_poll"),
    path("battles/<int:pk>/changing-room/", views.battle_changing_room, name="battle_changing_room"),
    path("battles/<int:pk>/changing-room/declare/", views.battle_declare_menu, name="battle_declare_menu"),
    path("battles/<int:pk>/biathlon/", views.biathlon, name="biathlon"),
    path("battles/<int:pk>/biathlon/lock/", views.biathlon_lock, name="biathlon_lock"),
    path("battles/<int:pk>/biathlon/shoot/", views.biathlon_shoot, name="biathlon_shoot"),
    path("moderation/cooking/", views.cooking_moderation, name="cooking_moderation"),
    path("battles/<int:pk>/moderation/cooking/approve/", views.cooking_moderation_approve, name="cooking_moderation_approve"),
    path("battles/<int:pk>/cooking/submit/", views.cooking_submit, name="cooking_submit"),
    path("hall-of-fame/", views.hall_of_fame, name="hall_of_fame"),
    path("battles/<int:pk>/ready/", views.battle_set_ready, name="battle_set_ready"),
    path("battles/<int:pk>/chat/send/", views.battle_chat_send, name="battle_chat_send"),
    path("battles/<int:pk>/chat/poll/", views.battle_chat_poll, name="battle_chat_poll"),
    path("profile/<slug:slug>/", views.chef_battle_profile, name="chef_profile"),
    path("battles/<int:pk>/gift/appreciation/", views.send_appreciation_gift_view, name="send_appreciation_gift"),
    path("battles/<int:pk>/gift/artifact/", views.send_viewer_battle_gift_view, name="send_viewer_battle_gift"),
    path("payout/", views.payout_statement, name="payout_statement"),
    path("payout/agreement/", views.reward_agreement, name="reward_agreement"),
    path("report/", views.content_report_submit, name="content_report_submit"),
    path("artifacts/", views.artifact_gallery, name="artifact_gallery"),
    path("artifacts/<int:pk>/generate/", views.artifact_generate_image, name="artifact_generate_image"),
    path("gifts/", views.appreciation_gallery, name="appreciation_gallery"),
    path("chest/", views.battle_chest, name="battle_chest"),
    path("changing-room/", views.changing_room, name="changing_room"),
    path("master/", views.master_console, name="master_console"),
    path("master/state/", views.master_state, name="master_state"),
    path("master/action/", views.master_action, name="master_action"),
]
