# Generated by Django 5.2.13 on 2026-05-30 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('reaction', models.CharField(choices=[('like', 'Like')], default='like', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content reaction',
                'verbose_name_plural': 'Content reactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'reaction'], name='collection__content_9c8209_idx'), models.Index(fields=['user', '-created_at'], name='collection__user_id_53e979_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id', 'reaction'), name='collection_content_reaction_unique')],
            },
        ),
        migrations.CreateModel(
            name='SavedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_content_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved content',
                'verbose_name_plural': 'Saved content',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='collection__content_0564ce_idx'), models.Index(fields=['user', '-saved_at'], name='collection__user_id_8c4b71_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='collection_saved_content_unique')],
            },
        ),
    ]
