# Generated by Django 5.2.13 on 2026-06-01 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_contentreaction_savedcontent'),
        ('recipes', '0035_recipeauthor_can_generate_ai_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='recipes.recipeauthor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author follow',
                'verbose_name_plural': 'Author follows',
                'ordering': ['-followed_at'],
                'indexes': [models.Index(fields=['user', '-followed_at'], name='collection__user_id_891edc_idx'), models.Index(fields=['author', '-followed_at'], name='collection__author__ac31c7_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'author'), name='collection_author_follow_unique')],
            },
        ),
    ]
