# Generated by Django 5.2.13 on 2026-05-28 11:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0016_article_category'),
        ('recipes', '0032_alter_recipe_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=16)),
                ('effect_type', models.CharField(blank=True, max_length=64)),
                ('effect_value', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CosmeticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('item_type', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('ended', 'Ended')], default='upcoming', max_length=16)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('battle_type', models.CharField(choices=[('recipe', 'Recipe Duel'), ('article', 'Article Duel'), ('mixed', 'Recipe Or Article')], default='recipe', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('proposed_start_time', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('refused_at', models.DateTimeField(blank=True, null=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_battle_challenges', to='recipes.recipeauthor')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_battle_challenges', to='recipes.recipeauthor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=180)),
                ('battle_type', models.CharField(choices=[('recipe', 'Recipe Duel'), ('article', 'Article Duel'), ('mixed', 'Recipe Or Article')], default='recipe', max_length=16)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('voting', 'Voting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=16)),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('submission_deadline', models.DateTimeField()),
                ('end_time', models.DateTimeField(db_index=True)),
                ('result_reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_challenger', to='recipes.recipeauthor')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_battles', to='recipes.recipeauthor')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_opponent', to='recipes.recipeauthor')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to='recipes.recipeauthor')),
                ('challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle', to='chef_battle.battlechallenge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_revealed', models.BooleanField(default=False)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_entries', to='articles.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_entries', to='recipes.recipeauthor')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='chef_battle.battle')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_entries', to='recipes.recipe')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('challenge_created', 'Challenge Created'), ('challenge_accepted', 'Challenge Accepted'), ('challenge_refused', 'Challenge Refused'), ('battle_started', 'Battle Started'), ('entry_submitted', 'Entry Submitted'), ('vote_cast', 'Vote Cast'), ('battle_completed', 'Battle Completed'), ('rank_promotion', 'Rank Promotion')], db_index=True, max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_public', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_events_as_actor', to='recipes.recipeauthor')),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chef_battle.battle')),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chef_battle.battlechallenge')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_events_as_target', to='recipes.recipeauthor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleMoveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_move_transactions', to='recipes.recipeauthor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chef_battle.battle')),
                ('voted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_votes_received', to='recipes.recipeauthor')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChefArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('equipped', models.BooleanField(default=False)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_artifacts', to='chef_battle.artifact')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_artifacts', to='recipes.recipeauthor')),
            ],
        ),
        migrations.CreateModel(
            name='ChefBattleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('kitchen_porter', 'Kitchen Porter'), ('prep_cook', 'Prep Cook'), ('commis_chef', 'Commis Chef'), ('chef_de_partie', 'Chef de Partie'), ('sous_chef', 'Sous Chef'), ('head_chef', 'Head Chef'), ('executive_chef', 'Executive Chef'), ('culinary_master', 'Culinary Master')], default='kitchen_porter', max_length=32)),
                ('rating', models.IntegerField(db_index=True, default=1000)),
                ('reputation', models.IntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('refused_battles', models.PositiveIntegerField(default=0)),
                ('win_streak', models.PositiveIntegerField(default=0)),
                ('crown_until', models.DateTimeField(blank=True, null=True)),
                ('battle_moves', models.PositiveIntegerField(default=0)),
                ('seasonal_score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle_profile', to='recipes.recipeauthor')),
            ],
            options={
                'ordering': ['-rating', '-wins', 'author__name'],
            },
        ),
        migrations.CreateModel(
            name='ChefCosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('equipped', models.BooleanField(default=False)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_cosmetics', to='recipes.recipeauthor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_cosmetics', to='chef_battle.cosmeticitem')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('rank_position', models.PositiveIntegerField(blank=True, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_standings', to='recipes.recipeauthor')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='chef_battle.season')),
            ],
            options={
                'ordering': ['rank_position', '-score'],
            },
        ),
        migrations.AddConstraint(
            model_name='battlechallenge',
            constraint=models.CheckConstraint(condition=models.Q(('challenger', models.F('opponent')), _negated=True), name='chef_battle_challenge_distinct_authors'),
        ),
        migrations.AddConstraint(
            model_name='battle',
            constraint=models.CheckConstraint(condition=models.Q(('challenger', models.F('opponent')), _negated=True), name='chef_battle_distinct_authors'),
        ),
        migrations.AddConstraint(
            model_name='battleentry',
            constraint=models.UniqueConstraint(fields=('battle', 'author'), name='one_battle_entry_per_author'),
        ),
        migrations.AddConstraint(
            model_name='battlevote',
            constraint=models.UniqueConstraint(condition=models.Q(('voter__isnull', False)), fields=('battle', 'voter'), name='one_authenticated_vote_per_battle'),
        ),
        migrations.AddConstraint(
            model_name='battlevote',
            constraint=models.UniqueConstraint(condition=models.Q(('voter__isnull', True), models.Q(('ip_hash', ''), _negated=True), models.Q(('user_agent_hash', ''), _negated=True)), fields=('battle', 'ip_hash', 'user_agent_hash'), name='one_anonymous_vote_per_battle_device'),
        ),
        migrations.AddConstraint(
            model_name='chefartifact',
            constraint=models.UniqueConstraint(fields=('chef', 'artifact'), name='unique_artifact_per_chef'),
        ),
        migrations.AddConstraint(
            model_name='chefcosmetic',
            constraint=models.UniqueConstraint(fields=('chef', 'item'), name='unique_cosmetic_per_chef'),
        ),
        migrations.AddConstraint(
            model_name='seasonstanding',
            constraint=models.UniqueConstraint(fields=('season', 'chef'), name='unique_season_standing_per_chef'),
        ),
    ]
