# Generated by Django 5.2.13 on 2026-06-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battleentry',
            old_name='note',
            new_name='battle_statement',
        ),
        migrations.AddField(
            model_name='battle',
            name='crown_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battle',
            name='rating_delta_challenger',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='rating_delta_opponent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='reveal_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='voting_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battlechallenge',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battleentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='battleentry',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battleentry',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='battleentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='battleevent',
            name='payload_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battlevote',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battlevote',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='battlevote',
            name='session_key_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='chefbattleprofile',
            name='best_win_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chefbattleprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chefbattleprofile',
            name='crown_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chefbattleprofile',
            name='ignored_battles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('awaiting_submissions', 'Awaiting Submissions'), ('revealed', 'Revealed'), ('voting', 'Voting'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], db_index=True, default='active', max_length=24),
        ),
        migrations.AlterField(
            model_name='battlechallenge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='battleevent',
            name='event_type',
            field=models.CharField(choices=[('challenge_created', 'Challenge Created'), ('challenge_accepted', 'Challenge Accepted'), ('challenge_refused', 'Challenge Refused'), ('challenge_expired', 'Challenge Expired'), ('battle_started', 'Battle Started'), ('entry_submitted', 'Entry Submitted'), ('battle_revealed', 'Battle Revealed'), ('vote_cast', 'Vote Cast'), ('battle_finished', 'Battle Finished'), ('battle_completed', 'Battle Completed'), ('chef_defeated', 'Chef Defeated'), ('crown_awarded', 'Crown Awarded'), ('rank_promoted', 'Rank Promoted')], db_index=True, max_length=32),
        ),
    ]
