# Generated by Django 5.2.13 on 2026-06-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0003_phase4_combat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('menu_locked', 'Menu Locked'), ('active', 'Active (Combat)'), ('awaiting_submissions', 'Awaiting Submissions'), ('revealed', 'Revealed'), ('cooking', 'Cooking'), ('presentation', 'Presentation'), ('voting', 'Voting'), ('completed', 'Completed'), ('ingredient_penalty', 'Ingredient Penalty'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], db_index=True, default='active', max_length=24),
        ),
    ]
