# Generated by Django 5.2.13 on 2026-06-11 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0004_add_battle_status_phases'),
        ('recipes', '0035_recipeauthor_can_generate_ai_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_index', models.PositiveSmallIntegerField(help_text="Zero-based line index in loser's recipe.ingredients")),
                ('bounced', models.BooleanField(default=False, help_text='True if the shot hit a lock and bounced')),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_shots', to='chef_battle.battle')),
                ('shooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_shots', to='recipes.recipeauthor')),
            ],
            options={
                'ordering': ['fired_at'],
            },
        ),
        migrations.CreateModel(
            name='IngredientLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_index', models.PositiveSmallIntegerField(help_text='Zero-based line index in recipe.ingredients')),
                ('is_revealed', models.BooleanField(default=False)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_locks', to='chef_battle.battle')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_locks', to='recipes.recipeauthor')),
            ],
            options={
                'ordering': ['placed_at'],
                'constraints': [models.UniqueConstraint(fields=('battle', 'chef', 'ingredient_index'), name='unique_lock_per_ingredient')],
            },
        ),
    ]
