# Generated by Django 5.2.13 on 2026-06-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0005_add_ingredient_lock_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefbattleprofile',
            name='is_hero',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='chefbattleprofile',
            name='level',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
    ]
