# Generated by Django 5.2.13 on 2026-06-11 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0006_chefbattleprofile_is_hero_chefbattleprofile_level'),
        ('recipes', '0035_recipeauthor_can_generate_ai_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('tokens', models.PositiveIntegerField()),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'tokens'],
            },
        ),
        migrations.CreateModel(
            name='TokenWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('total_purchased', models.PositiveIntegerField(default=0)),
                ('total_spent', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_wallet', to='recipes.recipeauthor')),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('purchase', 'Purchase'), ('gift_sent', 'Gift Sent'), ('gift_received', 'Gift Received'), ('artifact_bought', 'Artifact Bought'), ('refund', 'Refund'), ('admin_grant', 'Admin Grant'), ('admin_deduct', 'Admin Deduct')], db_index=True, max_length=20)),
                ('amount', models.IntegerField(help_text='Positive = credit, negative = debit')),
                ('balance_after', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_transactions', to='chef_battle.battle')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='chef_battle.tokenwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
