# Generated by Django 5.2.13 on 2026-06-11 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0007_tokenpackage_tokenwallet_tokentransaction'),
        ('recipes', '0035_recipeauthor_can_generate_ai_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='token_cost',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=16),
        ),
        migrations.AlterField(
            model_name='cosmeticitem',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=16),
        ),
        migrations.CreateModel(
            name='AppreciationGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_type', models.CharField(choices=[('flowers', 'Flowers'), ('coffee', 'Coffee'), ('beer', 'Beer'), ('cocktail', 'Cocktail'), ('whiskey', 'Whiskey')], max_length=16)),
                ('tokens_spent', models.PositiveIntegerField()),
                ('message', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciation_gifts', to='recipes.recipeauthor')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_appreciation_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewerBattleGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_spent', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_gifts', to='chef_battle.artifact')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_gifts', to='chef_battle.battle')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_battle_gifts', to='recipes.recipeauthor')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_battle_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
