# Generated by Django 5.2.13 on 2026-06-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0008_artifact_token_cost_alter_artifact_rarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleentry',
            name='cooked_photo',
            field=models.ImageField(blank=True, null=True, upload_to='chef_battle/cooked/'),
        ),
        migrations.AddField(
            model_name='battleentry',
            name='cooked_photo_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
