# Generated by Django 5.2.13 on 2026-06-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0009_battleentry_cooked_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefbattleprofile',
            name='michelin_stars',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
