# Generated by Django 5.2.13 on 2026-06-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0010_chefbattleprofile_michelin_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefbattleprofile',
            name='infinite_moves',
            field=models.BooleanField(default=False),
        ),
    ]
