# Generated by Django 5.2.13 on 2026-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0012_battlechatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefartifact',
            name='source',
            field=models.CharField(choices=[('purchased', 'Purchased'), ('gifted', 'Gifted'), ('drop', 'Battle Drop')], default='purchased', max_length=16),
        ),
        migrations.AlterField(
            model_name='battleevent',
            name='event_type',
            field=models.CharField(choices=[('challenge_created', 'Challenge Created'), ('challenge_accepted', 'Challenge Accepted'), ('challenge_refused', 'Challenge Refused'), ('challenge_expired', 'Challenge Expired'), ('battle_started', 'Battle Started'), ('entry_submitted', 'Entry Submitted'), ('battle_revealed', 'Battle Revealed'), ('vote_cast', 'Vote Cast'), ('battle_finished', 'Battle Finished'), ('battle_completed', 'Battle Completed'), ('chef_defeated', 'Chef Defeated'), ('crown_awarded', 'Crown Awarded'), ('rank_promoted', 'Rank Promoted'), ('artifact_dropped', 'Artifact Dropped')], db_index=True, max_length=32),
        ),
    ]
