# Generated by Django 5.2.13 on 2026-06-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0014_seed_token_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefbattleprofile',
            name='is_founding_chef',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
