# Generated by Django 5.2.13 on 2026-06-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0015_chefbattleprofile_is_founding_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefbattleprofile',
            name='prestige_title',
            field=models.CharField(blank=True, choices=[('', 'None'), ('challenger', 'The Challenger'), ('veteran', 'The Veteran'), ('iron_chef', 'The Iron Chef'), ('master', 'The Master'), ('legend', 'The Legend')], default='', max_length=16),
        ),
    ]
