# Generated by Django 5.2.13 on 2026-06-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0017_prestige_title_brigade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefbattleprofile',
            name='prestige_title',
            field=models.CharField(blank=True, choices=[('', 'None'), ('kitchen_porter', 'Kitchen Porter'), ('commis_chef', 'Commis Chef'), ('chef_de_partie', 'Chef de Partie'), ('sous_chef', 'Sous Chef'), ('head_chef', 'Head Chef'), ('incognito', 'Incognito')], default='', max_length=16),
        ),
    ]
