# Generated by Django 5.2.13 on 2026-06-14 10:42 (fixed: handle existing rows before unique)

from django.db import migrations, models


def _assign_keys_to_existing(apps, schema_editor):
    """Set a stable key on any existing packages before the unique index is created."""
    TokenPackage = apps.get_model("chef_battle", "TokenPackage")
    for pkg in TokenPackage.objects.filter(key=""):
        slug = pkg.name.lower().replace(" ", "_").replace("-", "_")
        pkg.key = f"legacy_{pkg.pk}_{slug}"[:40]
        pkg.save(update_fields=["key"])


class Migration(migrations.Migration):

    dependencies = [
        ("chef_battle", "0021_processedtokenstripeevent_tokenorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenpackage",
            name="discount_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        # Add key without unique first so existing blank rows don't clash.
        migrations.AddField(
            model_name="tokenpackage",
            name="key",
            field=models.CharField(blank=True, max_length=40, default=""),
            preserve_default=False,
        ),
        # Populate keys for any pre-existing rows.
        migrations.RunPython(_assign_keys_to_existing, migrations.RunPython.noop),
        # Now it's safe to add the unique constraint.
        migrations.AlterField(
            model_name="tokenpackage",
            name="key",
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="tokenpackage",
            name="price_eur",
            field=models.DecimalField(decimal_places=2, help_text="Final (discounted) price in EUR", max_digits=8),
        ),
    ]
