# Generated by Django 5.2.13 on 2026-06-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0021_processedtokenstripeevent_tokenorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenpackage',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tokenpackage',
            name='key',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenpackage',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, help_text='Final (discounted) price in EUR', max_digits=8),
        ),
    ]
