# Generated by Django 5.2.13 on 2026-06-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0023_token_packages_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenwallet',
            name='infinite_balance',
            field=models.BooleanField(default=False),
        ),
    ]
