# Generated by Django 5.2.13 on 2026-06-15 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0027_phase8_compliance_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerevent',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ledgerevent',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reward_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued for Review'), ('approved', 'Approved'), ('issued', 'Issued to Wallet'), ('acknowledged', 'Acknowledged by Recipient'), ('used', 'Used'), ('expired', 'Expired'), ('reversed', 'Reversed'), ('disputed', 'Under Dispute'), ('voided', 'Voided'), ('archived', 'Archived')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='status_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tokenorder',
            name='amount_net_cents',
            field=models.PositiveIntegerField(default=0, help_text='Pre-VAT amount in cents'),
        ),
        migrations.AddField(
            model_name='tokenorder',
            name='consent_text_snapshot',
            field=models.TextField(blank=True, help_text='Exact consent text shown to the buyer at purchase time, frozen for audit'),
        ),
        migrations.AddField(
            model_name='tokenorder',
            name='right_of_withdrawal_waived',
            field=models.BooleanField(default=False, help_text='Buyer explicitly waived 14-day right of withdrawal before instant token delivery'),
        ),
        migrations.AddField(
            model_name='tokenorder',
            name='vat_amount_cents',
            field=models.PositiveIntegerField(default=0, help_text='VAT portion in cents'),
        ),
        migrations.AddField(
            model_name='tokenorder',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default='0.2300', help_text='VAT rate applied at time of purchase (e.g. 0.2300 for 23%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tokenorder',
            name='withdrawal_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokenorder',
            name='amount_eur_cents',
            field=models.PositiveIntegerField(help_text='Total charged (net + VAT), in cents'),
        ),
    ]
