# Generated by Django 5.2.13 on 2026-06-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0028_reward_record_status_tokenorder_vat_ledger_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenorder',
            name='credited_at',
            field=models.DateTimeField(blank=True, help_text='When tokens were credited to the wallet', null=True),
        ),
        migrations.AddField(
            model_name='tokenorder',
            name='currency',
            field=models.CharField(default='eur', help_text='ISO 4217 currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='tokenorder',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Customer ID', max_length=255),
        ),
        migrations.AddField(
            model_name='tokenorder',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, help_text='Stripe Invoice ID if issued', max_length=255),
        ),
        migrations.AlterField(
            model_name='tokenorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('disputed', 'Under Dispute')], db_index=True, default='pending', max_length=16),
        ),
    ]
