# Generated by Django 5.2.13 on 2026-06-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0036_phase3_evidence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='image',
            field=models.ImageField(blank=True, upload_to='chef_battle/artifacts/'),
        ),
    ]
