# Generated by Django 5.2.13 on 2026-06-15 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0037_artifact_image_field'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlemovetransaction',
            name='reference_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='battlemovetransaction',
            name='reference_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battlemovetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('recipe_published', 'Recipe Publication'), ('article_published', 'Article Publication'), ('like_received', 'Verified Like Received'), ('battle_won', 'Victory Bonus'), ('battle_participation', 'Battle Participation'), ('combat_action_spent', 'Spent on Tactical Turn'), ('admin_adjustment', 'Admin Manual Fix')], default='admin_adjustment', max_length=30),
        ),
        migrations.AlterField(
            model_name='battlemovetransaction',
            name='reason',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
