# Generated by Django 5.2.13 on 2026-06-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0038_phase3_move_transaction_typed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='battle_type',
            field=models.CharField(choices=[('photo', 'Photo Battle'), ('video', 'Video Battle')], default='photo', max_length=16),
        ),
        migrations.AlterField(
            model_name='battlechallenge',
            name='battle_type',
            field=models.CharField(choices=[('photo', 'Photo Battle'), ('video', 'Video Battle')], default='photo', max_length=16),
        ),
        migrations.AlterField(
            model_name='rewardrecord',
            name='reward_type',
            field=models.CharField(choices=[('cbr', 'Chef Battles Reward'), ('lsr', 'Live Support Reward')], db_index=True, max_length=8),
        ),
    ]
