# Generated by Django 5.2.13 on 2026-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0039_remove_article_battle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardrecord',
            name='reward_type',
            field=models.CharField(choices=[('cbr', 'Chef Battle Reward'), ('lsr', 'Live Support Reward')], db_index=True, max_length=8),
        ),
    ]
