# Generated by Django 5.2.13 on 2026-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0040_add_enrolled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefbattleprofile',
            name='enrolled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
