# Generated by Django 5.2.13 on 2026-07-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0055_add_paused_battle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='paused_from_status',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='battle',
            name='paused_reason',
            field=models.TextField(blank=True),
        ),
    ]
