# Generated by Django 5.2.13 on 2026-07-05 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0057_voteintegrityevent'),
        ('recipes', '0038_recipeauthor_has_arena_console_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('flags', models.JSONField(blank=True, default=list, help_text='List of short flag strings raised by the operator')),
                ('recommendation', models.CharField(choices=[('approve_payout', 'Approve payout'), ('withhold', 'Withhold payout'), ('needs_review', 'Needs deeper review'), ('no_action', 'No action needed')], max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed by owner')], db_index=True, default='submitted', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_reports', to='recipes.recipeauthor')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_reports', to='chef_battle.battle')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_battle_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
