# Generated by Django 5.2.13 on 2026-07-05 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0058_battlereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleViewerPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_hash', models.CharField(db_index=True, max_length=64)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer_presences', to='chef_battle.battle')),
            ],
            options={
                'indexes': [models.Index(fields=['battle', 'last_seen_at'], name='viewer_battle_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('battle', 'viewer_hash'), name='unique_viewer_per_surface')],
            },
        ),
    ]
