# Generated by Django 5.2.13 on 2026-07-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0060_operatoractionidempotencykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecombataction',
            name='artifact_used',
            field=models.ForeignKey(blank=True, help_text='Artifact activated this round (consumed after resolution).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_uses', to='chef_battle.chefartifact'),
        ),
        migrations.AddField(
            model_name='battleentry',
            name='surviving_ingredients',
            field=models.JSONField(blank=True, default=list, help_text='Ingredient lines the chef may use in cooking (set by approve_cooking_phase).'),
        ),
        migrations.AlterField(
            model_name='battlemovetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('recipe_published', 'Recipe Publication'), ('article_published', 'Article Publication'), ('like_received', 'Verified Like Received'), ('battle_won', 'Victory Bonus'), ('battle_participation', 'Battle Participation'), ('combat_action_spent', 'Spent on Tactical Turn'), ('challenge_refused', 'Challenge Refusal Penalty'), ('admin_adjustment', 'Admin Manual Fix')], default='admin_adjustment', max_length=30),
        ),
    ]
