# Generated by Django 5.2.13 on 2026-07-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0065_battle_gift_artifact'),
        ('recipes', '0038_recipeauthor_has_arena_console_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlemovetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('recipe_published', 'Recipe Publication'), ('article_published', 'Article Publication'), ('like_received', 'Verified Like Received'), ('battle_won', 'Victory Bonus'), ('battle_participation', 'Battle Participation'), ('combat_action_spent', 'Spent on Tactical Turn'), ('challenge_refused', 'Challenge Refusal Penalty'), ('enrol_bonus', 'Enrolment Bonus'), ('admin_adjustment', 'Admin Manual Fix')], default='admin_adjustment', max_length=30),
        ),
        migrations.CreateModel(
            name='BattleIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_key', models.BooleanField(default=False, help_text='Hidden combat lock — protects this ingredient from elimination')),
                ('is_eliminated', models.BooleanField(db_index=True, default=False)),
                ('eliminated_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text="Display order within this chef's list")),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_ingredients', to='chef_battle.battle')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_ingredients', to='recipes.recipeauthor')),
                ('eliminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients_eliminated', to='recipes.recipeauthor')),
            ],
            options={
                'ordering': ['battle', 'chef', 'position'],
                'constraints': [models.UniqueConstraint(fields=('battle', 'chef', 'position'), name='unique_ingredient_position_per_chef')],
            },
        ),
    ]
