# Generated by Django 5.2.13 on 2026-07-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0066_alter_battlemovetransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlemovetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('recipe_published', 'Recipe Publication'), ('article_published', 'Article Publication'), ('pinch_published', 'Pinch Publication'), ('like_received', 'Verified Like Received'), ('battle_won', 'Victory Bonus'), ('battle_participation', 'Battle Participation'), ('combat_action_spent', 'Spent on Tactical Turn'), ('challenge_refused', 'Challenge Refusal Penalty'), ('enrol_bonus', 'Enrolment Bonus'), ('admin_adjustment', 'Admin Manual Fix')], default='admin_adjustment', max_length=30),
        ),
    ]
