# Generated by Django 5.2.13 on 2026-07-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0068_battlecombataction_target_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='battle',
            name='sponsor_tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='battle',
            name='sponsor_url',
            field=models.URLField(blank=True),
        ),
    ]
