# Generated by Django 5.2.13 on 2026-07-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0069_battle_sponsor_name_battle_sponsor_tagline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='sponsor_name',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='sponsor_tagline',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='sponsor_url',
        ),
    ]
