# Generated by Django 5.2.13 on 2026-07-13 22:16

import django.db.models.deletion
from django.db import migrations, models

_CUISINES = [
    ("Italian", "\U0001F1EE\U0001F1F9"), ("French", "\U0001F1EB\U0001F1F7"),
    ("Japanese", "\U0001F1EF\U0001F1F5"), ("Chinese", "\U0001F1E8\U0001F1F3"),
    ("Mexican", "\U0001F1F2\U0001F1FD"), ("Indian", "\U0001F1EE\U0001F1F3"),
    ("Greek", "\U0001F1EC\U0001F1F7"), ("Thai", "\U0001F1F9\U0001F1ED"),
    ("Korean", "\U0001F1F0\U0001F1F7"), ("American", "\U0001F1FA\U0001F1F8"),
]
_SPECIALTIES = [
    ("Bakery", "\U0001F956"), ("Pastry", "\U0001F950"), ("BBQ", "\U0001F525"),
    ("Grill", "\U0001F356"), ("Seafood", "\U0001F99E"), ("Street Food", "\U0001F32E"),
    ("Fine Dining", "\U0001F37D"), ("Fusion", "\U0001F372"), ("Molecular", "\U0001F9EA"),
    ("Vegetarian", "\U0001F957"), ("Vegan", "\U0001F331"), ("Fermentation", "\U0001FAD9"),
    ("Pizza", "\U0001F355"), ("Pasta", "\U0001F35D"), ("Sushi", "\U0001F363"),
    ("Desserts", "\U0001F370"), ("Coffee", "☕"), ("Cocktails", "\U0001F378"),
]


def seed_factions(apps, schema_editor):
    from django.utils.text import slugify
    Faction = apps.get_model("chef_battle", "Faction")
    for kind, items in (("cuisine", _CUISINES), ("specialty", _SPECIALTIES)):
        for name, icon in items:
            Faction.objects.update_or_create(
                kind=kind, slug=slugify(name),
                defaults={"name": name, "crest_icon": icon, "is_active": True},
            )


def unseed_factions(apps, schema_editor):
    Faction = apps.get_model("chef_battle", "Faction")
    Faction.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0070_remove_battle_sponsor_name_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('recipes', '0038_recipeauthor_has_arena_console_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cuisine', 'Cuisine'), ('specialty', 'Specialty')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80)),
                ('crest_icon', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'slug'), name='unique_faction_slug_per_kind')],
            },
        ),
        migrations.CreateModel(
            name='SeasonReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_snapshot', models.IntegerField(default=0)),
                ('placement', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_season_rewards', to='recipes.recipeauthor')),
                ('cosmetic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faction_season_rewards', to='chef_battle.chefcosmetic')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_rewards', to='chef_battle.faction')),
                ('reward_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faction_season_rewards', to='chef_battle.rewardrecord')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_rewards', to='chef_battle.season')),
            ],
        ),
        migrations.CreateModel(
            name='FactionContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_kind', models.CharField(choices=[('cuisine', 'Cuisine'), ('specialty', 'Specialty')], max_length=16)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_contributions', to='recipes.recipeauthor')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='chef_battle.faction')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_contributions', to='chef_battle.season')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['season', 'faction'], name='chef_battle_season__7615f6_idx'), models.Index(fields=['chef', 'season'], name='chef_battle_chef_id_8220e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_kind', models.CharField(choices=[('cuisine', 'Cuisine'), ('specialty', 'Specialty')], db_index=True, max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_memberships', to='recipes.recipeauthor')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chef_battle.faction')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_memberships', to='chef_battle.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chef', 'faction_kind', 'season'), name='unique_membership_per_kind_per_season')],
            },
        ),
        migrations.CreateModel(
            name='FactionSeasonStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('active_member_count', models.IntegerField(default=0)),
                ('normalized_score', models.FloatField(default=0.0)),
                ('rank_position', models.PositiveIntegerField(blank=True, null=True)),
                ('rewards_pending', models.BooleanField(default=False)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='chef_battle.faction')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_standings', to='chef_battle.season')),
            ],
            options={
                'ordering': ['rank_position', '-normalized_score'],
                'constraints': [models.UniqueConstraint(fields=('faction', 'season'), name='unique_standing_per_faction_per_season')],
            },
        ),
        migrations.RunPython(seed_factions, unseed_factions),
    ]
