# Generated by Django 5.2.13 on 2026-07-14 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0071_faction_seasonreward_factioncontribution_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('recipes', '0038_recipeauthor_has_arena_console_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('crest_icon', models.CharField(blank=True, max_length=8)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='clans', to='chef_battle.faction')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founded_clans', to='recipes.recipeauthor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AllianceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chef_battle.alliance')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliance_memberships', to='chef_battle.clan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('clan',), name='unique_active_alliance_per_clan')],
            },
        ),
        migrations.CreateModel(
            name='ClanContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_contributions', to='recipes.recipeauthor')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='chef_battle.clan')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_contributions', to='chef_battle.season')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['clan', 'season'], name='chef_battle_clan_id_1ec094_idx'), models.Index(fields=['chef', 'season'], name='chef_battle_chef_id_73ac41_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClanMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('member', 'Member')], default='member', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], db_index=True, default='pending', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_memberships', to='recipes.recipeauthor')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chef_battle.clan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('left_at__isnull', True), ('status', 'active')), fields=('chef',), name='unique_active_clan_per_chef')],
            },
        ),
        migrations.CreateModel(
            name='ClanSeasonStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('active_member_count', models.IntegerField(default=0)),
                ('rank_position', models.PositiveIntegerField(blank=True, null=True)),
                ('rewards_pending', models.BooleanField(default=False)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_standings', to='chef_battle.clan')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_standings', to='chef_battle.season')),
            ],
            options={
                'ordering': ['rank_position', '-total_points'],
                'constraints': [models.UniqueConstraint(fields=('clan', 'season'), name='unique_clan_standing_per_season')],
            },
        ),
    ]
