# Generated by Django 5.2.13 on 2026-07-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0072_alliance_clan_alliancemembership_clancontribution_and_more'),
        ('recipes', '0038_recipeauthor_has_arena_console_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonArenaObserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_observer_roles', to='recipes.recipeauthor')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_observers', to='chef_battle.clan')),
                ('nominated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arena_observer_nominations', to='recipes.recipeauthor')),
                ('won_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_observers', to='chef_battle.season')),
            ],
        ),
        migrations.CreateModel(
            name='ObserverDisputeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('approve_payout', 'Approve payout'), ('withhold', 'Withhold payout'), ('needs_review', 'Needs deeper review'), ('no_action', 'No action needed')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battle_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer_votes', to='chef_battle.battlereport')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_votes', to='chef_battle.seasonarenaobserver')),
            ],
        ),
        migrations.AddConstraint(
            model_name='seasonarenaobserver',
            constraint=models.UniqueConstraint(fields=('chef', 'won_season'), name='unique_observer_per_chef_per_won_season'),
        ),
        migrations.AddConstraint(
            model_name='observerdisputevote',
            constraint=models.UniqueConstraint(fields=('observer', 'battle_report'), name='unique_observer_vote_per_report'),
        ),
    ]
