# Generated by Django 5.2.13 on 2026-07-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0073_seasonarenaobserver_observerdisputevote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveArenaStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('phase_group', models.CharField(choices=[('foundation', 'Foundation'), ('frame', 'Frame'), ('live', 'Live modules'), ('crosscutting', 'Cross-cutting')], max_length=16)),
                ('backend_status', models.CharField(choices=[('absent', 'Absent'), ('partial', 'Partial'), ('present', 'Present')], default='absent', max_length=10)),
                ('frontend_status', models.CharField(choices=[('absent', 'Absent'), ('partial', 'Partial'), ('present', 'Present')], default='absent', max_length=10)),
                ('backend_notes', models.TextField(blank=True)),
                ('frontend_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
