# Generated by Django 5.2.13 on 2026-07-14 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0075_seed_live_arena_stages'),
        ('recipes', '0038_recipeauthor_has_arena_console_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('left', 'Left (challenger)'), ('right', 'Right (opponent)')], db_index=True, max_length=8)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_reactions', to='recipes.recipeauthor')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chef_battle.battle')),
            ],
            options={
                'indexes': [models.Index(fields=['battle', 'side'], name='chef_battle_battle__0f4653_idx'), models.Index(fields=['battle', 'created_at'], name='chef_battle_battle__e30cbf_idx')],
            },
        ),
    ]
