# Generated by Django 5.2.13 on 2026-07-15 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0077_alter_battleevent_event_type'),
        ('recipes', '0038_recipeauthor_has_arena_console_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlechallenge',
            name='theme_recipe',
            field=models.ForeignKey(blank=True, help_text="Recipe that inspired the challenge theme; it is never reused as the opponent's battle entry.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themed_battle_challenges', to='recipes.recipe'),
        ),
    ]
