# Generated by Django 5.2.13 on 2026-07-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0078_challenge_theme_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleentry',
            name='dish_submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the chef submitted the finished battle dish; recipe attachment alone is not a dish submission.', null=True),
        ),
    ]
