# Generated by Django 5.2.13 on 2026-07-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0080_registered_votes_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='waiting_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('menu_locked', 'Menu Locked'), ('active', 'Active (Combat)'), ('awaiting_submissions', 'Awaiting Submissions'), ('revealed', 'Revealed'), ('cooking', 'Cooking'), ('presentation', 'Presentation'), ('voting', 'Voting'), ('completed', 'Completed'), ('ingredient_penalty', 'Ingredient Penalty'), ('paused', 'Paused (Emergency Stop)'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('waiting', 'Waiting for the second chef'), ('walkover', 'Walkover (opponent never appeared)'), ('void', 'Void (neither chef appeared)')], db_index=True, default='active', max_length=24),
        ),
    ]
