# Generated by Django 5.2.13 on 2026-07-17 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0081_battle_waiting_until_alter_battle_status'),
        ('recipes', '0038_recipeauthor_has_arena_console_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlechallenge',
            name='theme_recipe',
            field=models.ForeignKey(blank=True, help_text="The challenger's own recipe for this battle. On accept it becomes the challenger's battle entry, so it must be one of their approved recipes. It is never reused as the opponent's entry: the opponent brings their own.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themed_battle_challenges', to='recipes.recipe'),
        ),
    ]
