# Generated by Django 5.2.13 on 2026-07-23 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0083_vote_self_vote_constraint_and_hash_scheme'),
        ('recipes', '0038_recipeauthor_has_arena_console_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_index', models.PositiveSmallIntegerField()),
                ('seat_index', models.PositiveSmallIntegerField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_seats', to='recipes.recipeauthor')),
            ],
            options={
                'indexes': [models.Index(fields=['released_at', 'ring_index', 'seat_index'], name='arena_seat_free_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('viewer',), name='unique_active_arena_seat_per_viewer'), models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('ring_index', 'seat_index'), name='unique_active_occupant_per_arena_seat')],
            },
        ),
    ]
