# Generated by Django 5.2.13 on 2026-08-05 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0084_arenaseat'),
        ('recipes', '0039_alter_recipeauthor_name_pen_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chefbattleprofile',
            name='withdrawals_remaining',
            field=models.PositiveSmallIntegerField(default=3, help_text='Force-majeure withdrawals left. Fixed allowance of 3 per account.'),
        ),
        migrations.CreateModel(
            name='BattleWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text="The withdrawing chef's own account of what happened.")),
                ('status', models.CharField(choices=[('awaiting_opponent', 'Waiting for the other chef'), ('awaiting_moderator', 'Waiting for a moderator'), ('closed', 'Closed')], db_index=True, default='awaiting_opponent', max_length=20)),
                ('opponent_decision', models.CharField(choices=[('pending', 'Waiting for the other chef'), ('without_penalty', 'Accepted without penalty'), ('with_penalty', 'Accepted with penalty')], db_index=True, default='pending', max_length=16)),
                ('opponent_reason', models.TextField(blank=True, help_text='Required only when the other chef asks for the penalty.')),
                ('opponent_decided_at', models.DateTimeField(blank=True, null=True)),
                ('moderator_note', models.TextField(blank=True)),
                ('penalty_applied', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='chef_battle.battle')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_withdrawals_received', to='recipes.recipeauthor')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_withdrawals_requested', to='recipes.recipeauthor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_battle_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('requester', models.F('opponent')), _negated=True), name='chef_battle_withdrawal_distinct_authors'), models.UniqueConstraint(condition=models.Q(('status', 'closed'), _negated=True), fields=('battle',), name='chef_battle_one_open_withdrawal_per_battle')],
            },
        ),
    ]
