# Generated by Django 5.2.13 on 2026-08-11 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0085_chefbattleprofile_withdrawals_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles', to='chef_battle.season'),
        ),
        migrations.AddField(
            model_name='battlemovetransaction',
            name='balance_after',
            field=models.PositiveIntegerField(blank=True, help_text='Move balance immediately after this entry. NULL for rows written before 2026-08-11.', null=True),
        ),
        migrations.AddField(
            model_name='seasonstanding',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstanding',
            name='streak',
            field=models.PositiveIntegerField(default=0, help_text='Longest run of consecutive wins inside this season.'),
        ),
        migrations.AddField(
            model_name='seasonstanding',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
