# Generated by Django 5.2.13 on 2026-08-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0086_audit_g9_g10_g12_ledger_balance_season_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleentry',
            name='cooking_format',
            field=models.CharField(choices=[('photos', 'Photo Series'), ('webcam', 'Live / Recorded Webcam')], default='photos', help_text='How this chef cooked the dish. Sets the artifact tier on a win.', max_length=16),
        ),
        migrations.AddField(
            model_name='season',
            name='crown_rule',
            field=models.CharField(blank=True, help_text='How the crown is decided for this season. Blank = the service default.', max_length=200),
        ),
        migrations.AddField(
            model_name='season',
            name='reward_rules_json',
            field=models.JSONField(blank=True, help_text='Per-season reward overrides. NULL = the service default.', null=True),
        ),
    ]
