# Generated by Django 5.2.13 on 2026-08-11 09:16

from django.db import migrations, models


def fill_slugs(apps, schema_editor):
    """Give every existing season a slug from its name.

    A unique blank SlugField is fine for one row and a UniqueViolation for two,
    so this runs in the same migration rather than being left to whoever creates
    the second season. Collisions are numbered, exactly as Season.save() does.
    """
    from django.utils.text import slugify
    Season = apps.get_model("chef_battle", "Season")
    taken = set()
    for season in Season.objects.order_by("pk"):
        if season.slug:
            taken.add(season.slug)
            continue
        base = slugify(season.name) or "season"
        candidate, n = base, 2
        while candidate in taken or Season.objects.filter(slug=candidate).exists():
            candidate, n = f"{base}-{n}", n + 1
        season.slug = candidate
        season.save(update_fields=["slug"])
        taken.add(candidate)


def drop_slugs(apps, schema_editor):
    """Reverse leg: the column goes with the field, so there is nothing to undo."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0087_audit_g3_g11_cooking_format_and_season_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.RunPython(fill_slugs, drop_slugs),
    ]
