# Generated by Django 5.2.13 on 2026-08-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0088_audit_g13_season_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefbattleprofile',
            name='rank',
            field=models.CharField(choices=[('kitchen_porter', 'Kitchen Porter'), ('prep_cook', 'Prep Cook'), ('commis_chef', 'Commis Chef'), ('chef_de_partie', 'Chef de Partie'), ('sous_chef', 'Sous Chef'), ('head_chef', 'Head Chef'), ('executive_chef', 'Executive Chef'), ('culinary_master', 'Culinary Master')], default='kitchen_porter', max_length=32),
        ),
    ]
