# Generated by Django 5.2.13 on 2026-08-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0089_x20_prep_cook_label'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='chef_battle_season_only_one_active'),
        ),
    ]
