# Generated by Django 5.2.13 on 2026-08-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0090_f24_season_only_one_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('processing', 'Processing (Stripe transfer in flight)'), ('rejected', 'Rejected'), ('on_hold', 'On Hold — Compliance'), ('paid', 'Paid Out'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16),
        ),
    ]
