# Generated by Django 5.2.13 on 2026-08-15 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0096_owner_arena_account_controls'),
        ('recipes', '0039_alter_recipeauthor_name_pen_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlechallenge',
            name='contested_recipe',
            field=models.ForeignKey(blank=True, help_text="The CHALLENGED chef's own recipe being contested. Set only when task_kind is CONTEST_RECIPE, and it must belong to the opponent.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contested_battle_challenges', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='battlechallenge',
            name='task_kind',
            field=models.CharField(choices=[('new_recipe', 'A completely new recipe'), ('contest_recipe', 'Contesting a recipe of the chef being challenged')], default='new_recipe', help_text='T19: what this challenge is fought over. Existing challenges predate the field and read as a new recipe, which is what they were.', max_length=20),
        ),
    ]
