# Generated by Django 5.2.13 on 2026-08-17 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0098_t11_shots_target_declared_ingredients'),
        ('recipes', '0039_alter_recipeauthor_name_pen_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=60)),
                ('body', models.CharField(max_length=300)),
                ('ring_index', models.PositiveSmallIntegerField()),
                ('seat_index', models.PositiveSmallIntegerField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arena_chat_messages', to='chef_battle.battle')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_chat_messages', to='recipes.recipeauthor')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['battle', 'id'], name='arena_chat_since_idx')],
            },
        ),
    ]
