# Generated by Django 5.2.13 on 2026-08-24 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0099_arenachatmessage'),
        ('recipes', '0040_recipeauthor_gallery_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='Short badge shown in chat, e.g. IRL. 2-5 capitals or digits.', max_length=5, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2,5}$', 'A tag is 2-5 characters, capitals and digits only - it has to fit a chat line on a phone.')]),
        ),
        migrations.AddField(
            model_name='clan',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='Short badge shown in chat, e.g. GOD. 2-5 capitals or digits.', max_length=5, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2,5}$', 'A tag is 2-5 characters, capitals and digits only - it has to fit a chat line on a phone.')]),
        ),
        migrations.AddConstraint(
            model_name='alliance',
            constraint=models.UniqueConstraint(condition=models.Q(('tag', ''), _negated=True), fields=('tag',), name='unique_alliance_tag_when_set'),
        ),
        migrations.AddConstraint(
            model_name='clan',
            constraint=models.UniqueConstraint(condition=models.Q(('tag', ''), _negated=True), fields=('tag',), name='unique_clan_tag_when_set'),
        ),
    ]
