# Generated by Django 5.2.13 on 2026-08-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0100_arena_chat_team_tags'),
        ('recipes', '0040_recipeauthor_gallery_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenachatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chef_battle.arenachatmessage'),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='content_kind',
            field=models.CharField(choices=[('battle_chat', 'Battle Chat Message'), ('battle_entry', 'Battle Entry'), ('chef_profile', 'Chef Profile'), ('arena_chat', 'Arena Chat Message')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ArenaChatReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('fire', 'Fire'), ('clap', 'Clap'), ('star', 'Star')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_chat_reactions', to='recipes.recipeauthor')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chef_battle.arenachatmessage')),
            ],
            options={
                'indexes': [models.Index(fields=['message', 'emoji'], name='chef_battle_message_6e9b8b_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'author', 'emoji'), name='one_reaction_per_person_per_emoji')],
            },
        ),
        migrations.CreateModel(
            name='ChatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocked_by', to='recipes.recipeauthor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks', to='recipes.recipeauthor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'blocked'), name='one_block_per_pair'), models.CheckConstraint(condition=models.Q(('owner', models.F('blocked')), _negated=True), name='no_self_block')],
            },
        ),
        migrations.CreateModel(
            name='ChatMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_muted_by', to='recipes.recipeauthor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_mutes', to='recipes.recipeauthor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'muted'), name='one_mute_per_pair'), models.CheckConstraint(condition=models.Q(('owner', models.F('muted')), _negated=True), name='no_self_mute')],
            },
        ),
    ]
