# Generated by Django 5.2.13 on 2026-08-24 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0101_arena_chat_interactions'),
        ('recipes', '0040_recipeauthor_gallery_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('direct', 'Direct')], db_index=True, default='direct', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='chefbattleprofile',
            name='dm_policy',
            field=models.CharField(choices=[('anyone', 'Anyone in the hall'), ('team', 'My clan and alliance only'), ('nobody', 'Nobody')], default='anyone', help_text='Who may start a private conversation with this chef.', max_length=8),
        ),
        migrations.AddField(
            model_name='arenachatmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chef_battle.chatconversation'),
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='recipes.recipeauthor')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chef_battle.chatconversation')),
            ],
            options={
                'indexes': [models.Index(fields=['author', 'conversation'], name='chef_battle_author__1be236_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'author'), name='one_seat_per_conversation')],
            },
        ),
    ]
