# Generated by Django 5.2.13 on 2026-08-24 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0102_arena_chat_direct_messages'),
        ('recipes', '0040_recipeauthor_gallery_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arenachatmessage',
            options={'ordering': ['created_at', 'id'], 'permissions': [('moderate_arena_chat', 'Can hide and restore arena chat messages'), ('timeout_arena_chat_user', 'Can temporarily silence a chef in arena chat'), ('resolve_arena_chat_report', 'Can resolve arena chat reports')]},
        ),
        migrations.CreateModel(
            name='ArenaChatTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_chat_timeouts', to='recipes.recipeauthor')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arena_chat_timeouts_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hide', 'Hide message'), ('restore', 'Restore message'), ('timeout', 'Timeout user')], db_index=True, max_length=16)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('previous_state', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arena_chat_moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arena_chat_moderation_received', to='recipes.recipeauthor')),
                ('target_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='chef_battle.arenachatmessage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_author', 'created_at'], name='chef_battle_target__c0299f_idx')],
            },
        ),
    ]
