# Generated by Django 5.2.13 on 2026-08-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0103_arena_chat_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenachatreaction',
            name='emoji',
            field=models.CharField(choices=[('fire', 'Fire'), ('clap', 'Clap'), ('star', 'Star'), ('smile', 'Smile'), ('laugh', 'Laugh'), ('heart', 'Heart'), ('wow', 'Wow')], max_length=8),
        ),
    ]
