# Generated by Django 5.2.13 on 2026-08-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0104_alter_arenachatreaction_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenachatmessage',
            name='media',
            field=models.FileField(blank=True, help_text='Stored re-encoded; never the bytes that were uploaded.', upload_to='chef_battle/chat/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='arenachatmessage',
            name='media_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenachatmessage',
            name='media_kind',
            field=models.CharField(blank=True, choices=[('', 'No attachment'), ('image', 'Picture'), ('animation', 'Animation')], default='', max_length=9),
        ),
        migrations.AddField(
            model_name='arenachatmessage',
            name='media_poster',
            field=models.FileField(blank=True, upload_to='chef_battle/chat/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='arenachatmessage',
            name='media_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
