# Generated by Django 5.2.13 on 2026-08-26 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0105_arenachatmessage_media_arenachatmessage_media_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenachatmessage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arena_chat_cards', to='chef_battle.battleevent'),
        ),
        migrations.AddField(
            model_name='arenachatmessage',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Spoken line'), ('challenge_issued', 'Challenge issued'), ('voting_open', 'Voting opened'), ('battle_result', 'Battle result')], default='', max_length=24),
        ),
    ]
