# Generated by Django 5.2.13 on 2026-08-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0106_arenachatmessage_event_arenachatmessage_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenachatmessage',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Spoken line'), ('challenge_issued', 'Challenge issued'), ('voting_open', 'Voting opened'), ('battle_result', 'Battle result'), ('ingredient_attack', 'Ingredient struck off'), ('defence', 'Shot blocked')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='battleevent',
            name='event_type',
            field=models.CharField(choices=[('challenge_created', 'Challenge Created'), ('challenge_accepted', 'Challenge Accepted'), ('challenge_refused', 'Challenge Refused'), ('challenge_expired', 'Challenge Expired'), ('battle_started', 'Battle Started'), ('menu_locked', 'Menu Locked (both ready)'), ('entry_submitted', 'Entry Submitted'), ('battle_revealed', 'Battle Revealed'), ('vote_cast', 'Vote Cast'), ('battle_finished', 'Battle Finished'), ('battle_completed', 'Battle Completed'), ('ingredient_hit', 'Ingredient Struck Off'), ('ingredient_blocked', 'Ingredient Shot Blocked'), ('chef_defeated', 'Chef Defeated'), ('crown_awarded', 'Crown Awarded'), ('rank_promoted', 'Rank Promoted'), ('artifact_dropped', 'Artifact Dropped'), ('operator_action', 'Operator Action')], db_index=True, max_length=32),
        ),
    ]
