# Generated by Django 5.2.13 on 2026-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0107_alter_arenachatmessage_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenachatmessage',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Spoken line'), ('challenge_issued', 'Challenge issued'), ('voting_open', 'Voting opened'), ('battle_result', 'Battle result'), ('ingredient_attack', 'Ingredient struck off'), ('defence', 'Shot blocked'), ('chef_entered', 'Chef entered the Arena')], default='', max_length=24),
        ),
    ]
