# Generated by Django 5.2.13 on 2026-08-26 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0108_alter_arenachatmessage_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenachatmessage',
            name='combat_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arena_chat_cards', to='chef_battle.battleround'),
        ),
        migrations.AlterField(
            model_name='arenachatmessage',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Spoken line'), ('challenge_issued', 'Challenge issued'), ('voting_open', 'Voting opened'), ('battle_result', 'Battle result'), ('ingredient_attack', 'Ingredient struck off'), ('defence', 'Shot blocked'), ('chef_entered', 'Chef entered the Arena'), ('artifact_attack', 'Artifact attack landed'), ('artifact_defence', 'Artifact defence held')], default='', max_length=24),
        ),
    ]
