# Generated by Django 5.2.13 on 2026-08-26 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0109_arenachatmessage_combat_round_and_more'),
        ('recipes', '0040_recipeauthor_gallery_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenachatmessage',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Spoken line'), ('challenge_issued', 'Challenge issued'), ('voting_open', 'Voting opened'), ('battle_result', 'Battle result'), ('ingredient_attack', 'Ingredient struck off'), ('defence', 'Shot blocked'), ('chef_entered', 'Chef entered the Arena'), ('artifact_attack', 'Artifact attack landed'), ('artifact_defence', 'Artifact defence held'), ('poll', 'Poll')], default='', max_length=24),
        ),
        migrations.CreateModel(
            name='ArenaChatPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closes_at', models.DateTimeField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='chef_battle.arenachatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ArenaChatPollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='chef_battle.arenachatpoll')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArenaChatPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chef_battle.arenachatpolloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chef_battle.arenachatpoll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_chat_poll_votes', to='recipes.recipeauthor')),
            ],
        ),
        migrations.AddIndex(
            model_name='arenachatpoll',
            index=models.Index(fields=['closes_at'], name='chef_battle_closes__6ceea1_idx'),
        ),
        migrations.AddIndex(
            model_name='arenachatpollvote',
            index=models.Index(fields=['option'], name='chef_battle_option__efe871_idx'),
        ),
        migrations.AddConstraint(
            model_name='arenachatpollvote',
            constraint=models.UniqueConstraint(fields=('poll', 'voter'), name='one_poll_answer_per_person'),
        ),
    ]
