# Generated by Django 5.2.13 on 2026-08-27 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0110_alter_arenachatmessage_kind_arenachatpoll_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaHouseStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playback_url', models.URLField(blank=True, help_text='HLS manifest (.m3u8). Left empty, the widget shows the off-air card.', max_length=500)),
                ('title', models.CharField(blank=True, help_text='Shown over the picture. Empty falls back to The house kitchen.', max_length=80)),
                ('caption', models.CharField(blank=True, help_text='One quiet line under the title. Optional.', max_length=160)),
                ('is_live', models.BooleanField(default=False, help_text='Off shows the off-air card even when a URL is set.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_stream_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arena house stream',
                'verbose_name_plural': 'Arena house stream',
            },
        ),
    ]
