# Generated by Django 5.2.13 on 2026-08-27 20:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0111_arenahousestream'),
        ('recipes', '0040_recipeauthor_gallery_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('token_cost', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='tx_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('gift_sent', 'Gift Sent'), ('gift_received', 'Gift Received'), ('artifact_bought', 'Artifact Bought'), ('cosmetic_bought', 'Cosmetic Bought'), ('refund', 'Refund'), ('admin_grant', 'Admin Grant'), ('admin_deduct', 'Admin Deduct')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='StickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='A sticker token is 2-32 characters of a-z, 0-9 and underscore.', regex='^[a-z0-9_]{2,32}$')])),
                ('label', models.CharField(max_length=60)),
                ('token_cost', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stickers', to='chef_battle.stickerpack')),
            ],
            options={
                'ordering': ['sort_order', 'token'],
            },
        ),
        migrations.CreateModel(
            name='ChefSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('single', 'Bought on its own'), ('pack', 'Bought as part of a pack'), ('grant', 'Granted by a moderator')], default='single', max_length=8)),
                ('grant_reason', models.CharField(blank=True, max_length=200)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_stickers', to='recipes.recipeauthor')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_chef_stickers', to=settings.AUTH_USER_MODEL)),
                ('token_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chef_stickers', to='chef_battle.tokentransaction')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='chef_battle.stickeritem')),
            ],
            options={
                'ordering': ['sticker__sort_order', 'sticker__token'],
                'constraints': [models.UniqueConstraint(fields=('chef', 'sticker'), name='unique_sticker_per_chef')],
            },
        ),
    ]
