# Generated by Django 5.2.13 on 2026-08-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0113_seed_sticker_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickeritem',
            name='sold_separately',
            field=models.BooleanField(default=False, help_text='Shown with its pack, but the pack price does not grant it.'),
        ),
    ]
