# Generated by Django 5.2.13 on 2026-08-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0115_noooo_is_sold_separately'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenahousestream',
            name='title',
            field=models.CharField(blank=True, help_text='Shown over the picture. Empty falls back to BearCave Food Trailer.', max_length=80),
        ),
    ]
