# Generated by Django 5.2.13 on 2026-09-02 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0117_drop_the_july_test_artifact_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaOperatorFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_emulation_bots', models.BooleanField(default=False, help_text='Whether the two EMU bot chefs stand on the arena floor.')),
                ('chat_is_open', models.BooleanField(default=True, help_text='Off closes the arena chat TO NEW LINES. The panel, the history and the private threads all stay exactly where they are.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arena_flag_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arena operator flags',
                'verbose_name_plural': 'Arena operator flags',
            },
        ),
    ]
