# Generated by Django 5.2.13 on 2026-09-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0118_arena_operator_flags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveArenaStage',
        ),
    ]
