# Generated by Django 5.2.13 on 2026-09-04 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0119_drop_live_arena_stage'),
        ('recipes', '0040_recipeauthor_gallery_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RehearsalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('scenario', models.CharField(choices=[('A', 'A - battle lifecycle')], default='A', max_length=2)),
                ('seed', models.BigIntegerField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('blocked', 'Blocked on a missing mechanism'), ('passed', 'Passed'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='running', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_tainted', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehearsal_runs', to='chef_battle.battle')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehearsal_runs', to='recipes.recipeauthor')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RehearsalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('outcome', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('missing_mechanism', 'Missing mechanism'), ('ui_mismatch', 'UI mismatch'), ('forced', 'Stepped over by the operator')], max_length=20)),
                ('mechanism', models.CharField(blank=True, max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='chef_battle.rehearsalrun')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'unique_together': {('run', 'position')},
            },
        ),
    ]
