# Generated by Django 5.2.13 on 2026-09-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0120_rehearsal_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='presentation_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
