# Generated by Django 5.2.13 on 2026-09-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0122_artifact_delivered_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehearsalrun',
            name='scenario',
            field=models.CharField(choices=[('A', 'A - battle lifecycle'), ('B', 'B - battle with artifacts'), ('C', 'C - the stands: delivery, gifts, chat'), ('D', 'D - shop, chest and drops'), ('E', 'E - a full hall'), ('F', "F - the spectator's window"), ('G', 'G - the result frame'), ('H', 'H - what the battle leaves behind')], default='A', max_length=2),
        ),
    ]
