# Generated by Django 5.2.13 on 2026-09-04 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0123_rehearsal_scenarios'),
        ('recipes', '0040_recipeauthor_gallery_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefFanClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('left_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_club_members', to='recipes.recipeauthor')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_club_memberships', to='recipes.recipeauthor')),
            ],
            options={
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['chef', 'left_at'], name='chef_battle_chef_id_f103ce_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('viewer', 'chef'), name='one_live_fan_club_membership_per_pair'), models.CheckConstraint(condition=models.Q(('viewer', models.F('chef')), _negated=True), name='a_chef_is_not_his_own_fan')],
            },
        ),
    ]
