# Generated by Django 5.2.13 on 2026-09-04 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0124_fan_club'),
        ('recipes', '0040_recipeauthor_gallery_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenachatmessage',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arena_chat_messages', to='recipes.recipeauthor'),
        ),
    ]
