# Generated by Django 5.2.13 on 2026-09-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_battle', '0125_arena_chat_speaker_may_be_the_arena'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='fee_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee the payment provider actually charged, read back after the transfer', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='net_payout_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Gross minus the provider's fee, once the fee is known", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='stripe_balance_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
