# Generated by Django 5.2.13 on 2026-06-20 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoworkingAgent',
            fields=[
                ('agent_id', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('blocked', 'Blocked')], default='idle', max_length=16)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('task_title', models.CharField(blank=True, max_length=255)),
                ('task_description', models.TextField(blank=True)),
                ('task_branch', models.CharField(blank=True, max_length=120)),
                ('task_files_touched', models.JSONField(blank=True, default=list)),
                ('task_next_step', models.TextField(blank=True)),
                ('task_started_at', models.DateTimeField(blank=True, null=True)),
                ('active_prompt', models.TextField(blank=True)),
                ('key_facts', models.JSONField(blank=True, default=list)),
                ('decisions_made', models.JSONField(blank=True, default=list)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['agent_id'],
            },
        ),
        migrations.CreateModel(
            name='CoworkingSharedMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_memory', models.JSONField(blank=True, default=list)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('completed_today', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coworking shared memory',
                'verbose_name_plural': 'Coworking shared memory',
            },
        ),
        migrations.CreateModel(
            name='CoworkingLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('action', models.TextField()),
                ('result', models.CharField(choices=[('ok', 'OK'), ('blocked', 'Blocked'), ('pending', 'Pending')], default='ok', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='coworking.coworkingagent')),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
