# Generated by Django 5.2.13 on 2026-07-13 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0002_remove_fake_handoffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoworkingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('from_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='coworking.coworkingagent')),
                ('to_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='coworking.coworkingagent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_agent', 'read_at'], name='coworking_c_to_agen_1800fb_idx')],
            },
        ),
    ]
