# Generated by Django 5.2.13 on 2026-07-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0003_coworkingmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworkingmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
