# Generated by Django 5.2.13 on 2026-06-04 11:51

import django.db.models.deletion
import django.utils.timezone
import recipes.validators
import uuid
from django.conf import settings
from django.db import migrations, models


ROADMAP_MILESTONES = [
    "Audit existing Sponsors section",
    "Update sponsor data model",
    "Add VAT-aware pricing display",
    "Add sponsor application form updates",
    "Add sponsor cell locking",
    "Add Stripe Checkout Session creation",
    "Add Stripe webhook handling",
    "Add payment status tracking",
    "Add paid pending approval workflow",
    "Add approval and publication workflow",
    "Add rejection and refund-required workflow",
    "Update annual sponsorship terms wording",
    "Add success and cancel pages",
    "Add moderation dashboard views",
    "Add super-admin roadmap page",
    "Add audit logging",
    "Add tests",
    "Complete test-mode Stripe payment",
    "Complete webhook test",
    "Prepare live-mode checklist",
]


def seed_sponsor_roadmap_items(apps, schema_editor):
    SponsorRoadmapItem = apps.get_model("sponsors", "SponsorRoadmapItem")
    now = django.utils.timezone.now()
    for index, title in enumerate(ROADMAP_MILESTONES, start=1):
        is_done = index <= 17
        SponsorRoadmapItem.objects.get_or_create(
            title=title,
            defaults={
                "phase": "Stripe Sponsors",
                "sort_order": index,
                "status": "done" if is_done else "not_started",
                "priority": "high" if index <= 17 else "medium",
                "completed_at": now if is_done else None,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_sponsor_cell_enquiry_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorRoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('phase', models.CharField(default='Stripe Sponsors', max_length=100)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('ready_for_test', 'Ready for test'), ('done', 'Done'), ('skipped', 'Skipped')], db_index=True, default='not_started', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_blocker', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.RunPython(seed_sponsor_roadmap_items, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sponsorcell',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('payment_pending', 'Payment pending'), ('paid_pending_approval', 'Paid pending approval'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('unavailable', 'Unavailable'), ('reserved', 'Reserved (legacy)'), ('sold', 'Sold (legacy)')], db_index=True, default='available', max_length=32),
        ),
        migrations.CreateModel(
            name='SponsorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('payment_pending', 'Payment pending'), ('paid_pending_approval', 'Paid pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_required', 'Refund required'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='draft', max_length=32)),
                ('sponsor_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website_url', models.URLField()),
                ('logo', models.ImageField(upload_to='sponsors/applications/', validators=[recipes.validators.ImageUploadValidator(max_size=5242880)])),
                ('sponsor_note', models.TextField(blank=True)),
                ('logo_offset_x', models.FloatField(default=0.0)),
                ('logo_offset_y', models.FloatField(default=0.0)),
                ('logo_scale', models.FloatField(default=1.0)),
                ('price_net_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='eur', max_length=3)),
                ('logo_rights_confirmed', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('approval_acknowledged', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_version', models.CharField(default='2026-06-04-stripe-sponsors-v1', max_length=80)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sponsor_applications', to=settings.AUTH_USER_MODEL)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='sponsors.sponsorcell')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_sponsor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedStripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_events', to='sponsors.sponsorapplication')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('application_created', 'Application created'), ('checkout_created', 'Checkout created'), ('checkout_failed', 'Checkout failed'), ('checkout_cancelled', 'Checkout cancelled'), ('checkout_expired', 'Checkout expired'), ('payment_confirmed', 'Payment confirmed'), ('payment_failed', 'Payment failed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_required', 'Refund required'), ('refund_completed', 'Refund completed'), ('unpublished', 'Unpublished'), ('expired', 'Expired')], db_index=True, max_length=64)),
                ('from_status', models.CharField(blank=True, max_length=64)),
                ('to_status', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='sponsors.sponsorapplication')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='sponsors.sponsorcell')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], db_index=True, default='pending', max_length=32)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('net_amount_cents', models.PositiveIntegerField(default=0)),
                ('vat_amount_cents', models.PositiveIntegerField(default=0)),
                ('total_amount_cents', models.PositiveIntegerField(default=0)),
                ('refunded_amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='eur', max_length=3)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='sponsors.sponsorapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sponsorapplication',
            index=models.Index(fields=['status', 'created_at'], name='sponsors_sp_status_f65ead_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorapplication',
            index=models.Index(fields=['cell', 'status'], name='sponsors_sp_cell_id_fd404a_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorauditlog',
            index=models.Index(fields=['action', 'created_at'], name='sponsors_sp_action_139b12_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorauditlog',
            index=models.Index(fields=['application', 'created_at'], name='sponsors_sp_applica_9c3345_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorpayment',
            index=models.Index(fields=['status', 'created_at'], name='sponsors_sp_status_9cff69_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorpayment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='sponsors_sp_stripe__112bde_idx'),
        ),
    ]
