# Generated by Django 5.2.13 on 2026-06-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_alter_sponsorapplication_website_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sponsorpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_payment_intent_id', ''), _negated=True), fields=('stripe_payment_intent_id',), name='unique_nonempty_stripe_payment_intent_id'),
        ),
    ]
