# Generated by Django 5.2.13 on 2026-06-06 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0008_changes_requested_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorapplication',
            name='terms_version',
            field=models.CharField(default='2026-06-06-compliance-v1', max_length=80),
        ),
        migrations.AlterField(
            model_name='sponsorauditlog',
            name='action',
            field=models.CharField(choices=[('application_created', 'Application created'), ('checkout_created', 'Checkout created'), ('checkout_failed', 'Checkout failed'), ('checkout_cancelled', 'Checkout cancelled'), ('checkout_expired', 'Checkout expired'), ('payment_confirmed', 'Payment confirmed'), ('payment_failed', 'Payment failed'), ('changes_requested', 'Changes requested'), ('ready_for_review', 'Ready for review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_required', 'Refund required'), ('refund_completed', 'Refund completed'), ('unpublished', 'Unpublished'), ('expired', 'Expired'), ('compliance_check_clear', 'Compliance check clear'), ('compliance_possible_match', 'Compliance possible match'), ('compliance_blocked', 'Compliance blocked'), ('compliance_false_positive_cleared', 'Compliance false positive cleared'), ('compliance_error', 'Compliance error')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='SanctionsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('eu', 'EU Consolidated Financial Sanctions List'), ('un', 'UN Security Council Consolidated List'), ('manual', 'Manual compliance entry')], db_index=True, max_length=16)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('listed_on', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_sanctions_source_external_id')],
            },
        ),
        migrations.CreateModel(
            name='SponsorComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_checked', 'Not checked'), ('clear', 'Compliance clear'), ('possible_match', 'Possible sanctions match'), ('confirmed_match', 'Confirmed sanctions match'), ('false_positive_cleared', 'False positive cleared'), ('blocked', 'Blocked'), ('error', 'Screening error')], db_index=True, default='not_checked', max_length=32)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('source_summary', models.CharField(blank=True, max_length=500)),
                ('matched_name', models.CharField(blank=True, max_length=255)),
                ('matched_source', models.CharField(blank=True, max_length=100)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('checked_payload', models.JSONField(blank=True, default=dict)),
                ('raw_matches', models.JSONField(blank=True, default=list)),
                ('staff_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='sponsors.sponsorapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
