# Generated by Django 5.2.13 on 2026-06-06 01:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0009_alter_sponsorapplication_terms_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorApplicantDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_text', models.JSONField(default=list)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('sponsor_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SanctionsEntry',
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('payment_pending', 'Payment pending'), ('paid_pending_compliance_review', 'Payment received pending compliance review'), ('paid_pending_approval', 'Paid pending approval'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_required', 'Refund required'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='terms_version',
            field=models.CharField(default='2026-06-06-compliance-phase1-v1', max_length=80),
        ),
        migrations.AlterField(
            model_name='sponsorauditlog',
            name='action',
            field=models.CharField(choices=[('application_created', 'Application created'), ('checkout_created', 'Checkout created'), ('checkout_created_after_declaration', 'Checkout created after declaration'), ('checkout_failed', 'Checkout failed'), ('checkout_cancelled', 'Checkout cancelled'), ('checkout_expired', 'Checkout expired'), ('payment_confirmed', 'Payment confirmed'), ('applicant_declaration_accepted', 'Applicant declaration accepted'), ('payment_received_pending_compliance_review', 'Payment received pending compliance review'), ('manual_compliance_clear', 'Manual compliance clear'), ('payment_failed', 'Payment failed'), ('changes_requested', 'Changes requested'), ('ready_for_review', 'Ready for review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_required', 'Refund required'), ('refund_completed', 'Refund completed'), ('unpublished', 'Unpublished'), ('expired', 'Expired'), ('compliance_blocked', 'Compliance blocked')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='sponsorcompliancecheck',
            name='status',
            field=models.CharField(choices=[('not_checked', 'Not checked'), ('self_declared', 'Applicant declaration accepted'), ('screening_required', 'Manual compliance review required'), ('clear', 'Compliance clear'), ('manually_cleared', 'Manually reviewed and clear'), ('blocked', 'Blocked')], db_index=True, default='not_checked', max_length=32),
        ),
        migrations.AddField(
            model_name='sponsorapplicantdeclaration',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_declaration', to='sponsors.sponsorapplication'),
        ),
    ]
