# Generated by Django 5.2.13 on 2026-06-06 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0010_sponsorapplicantdeclaration_delete_sanctionsentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionsSourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(choices=[('eu_fsf', 'EU Financial Sanctions Files'), ('un_sc_consolidated', 'UN Security Council Consolidated List')], db_index=True, max_length=32)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(max_length=1000)),
                ('file_format', models.CharField(default='xml', max_length=16)),
                ('fetched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('source_etag', models.CharField(blank=True, max_length=255)),
                ('source_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('stale', 'Stale'), ('skipped_not_modified', 'Skipped not modified')], db_index=True, max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='sanctions/sources/')),
                ('parser_version', models.CharField(default='phase2-xml-v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_code', 'status', 'fetched_at'], name='sponsors_sa_source__ba574c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SanctionsSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(choices=[('eu_fsf', 'EU Financial Sanctions Files'), ('un_sc_consolidated', 'UN Security Council Consolidated List')], db_index=True, max_length=32)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('subject_type', models.CharField(choices=[('individual', 'Individual'), ('entity', 'Entity'), ('vessel', 'Vessel'), ('aircraft', 'Aircraft'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32)),
                ('primary_name', models.CharField(max_length=500)),
                ('normalised_name', models.CharField(db_index=True, max_length=500)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('countries', models.JSONField(blank=True, default=list)),
                ('dates_of_birth', models.JSONField(blank=True, default=list)),
                ('identifiers', models.JSONField(blank=True, default=list)),
                ('regimes', models.JSONField(blank=True, default=list)),
                ('measures', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='sponsors.sanctionssourcesnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['source_code', 'normalised_name'], name='sponsors_sa_source__42500f_idx'), models.Index(fields=['source_code', 'external_reference'], name='sponsors_sa_source__6b7c44_idx')],
            },
        ),
    ]
