# Generated by Django 5.2.13 on 2026-06-06 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0011_sanctionssourcesnapshot_sanctionssubject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorauditlog',
            name='action',
            field=models.CharField(choices=[('application_created', 'Application created'), ('checkout_created', 'Checkout created'), ('checkout_created_after_declaration', 'Checkout created after declaration'), ('checkout_failed', 'Checkout failed'), ('checkout_cancelled', 'Checkout cancelled'), ('checkout_expired', 'Checkout expired'), ('payment_confirmed', 'Payment confirmed'), ('applicant_declaration_accepted', 'Applicant declaration accepted'), ('payment_received_pending_compliance_review', 'Payment received pending compliance review'), ('manual_compliance_clear', 'Manual compliance clear'), ('payment_failed', 'Payment failed'), ('changes_requested', 'Changes requested'), ('ready_for_review', 'Ready for review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_required', 'Refund required'), ('refund_completed', 'Refund completed'), ('unpublished', 'Unpublished'), ('expired', 'Expired'), ('compliance_blocked', 'Compliance blocked'), ('sanctions_screening_completed', 'Sanctions screening completed'), ('sanctions_possible_match_created', 'Sanctions possible match created'), ('sanctions_match_false_positive', 'Sanctions match marked false positive'), ('sanctions_match_manually_cleared', 'Sanctions match manually cleared'), ('sanctions_match_blocked', 'Sanctions match blocked'), ('approval_blocked_sanctions', 'Approval blocked by sanctions review')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='SponsorSanctionsMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(choices=[('eu_fsf', 'EU Financial Sanctions Files'), ('un_sc_consolidated', 'UN Security Council Consolidated List')], db_index=True, max_length=32)),
                ('match_status', models.CharField(choices=[('possible', 'Possible sanctions match'), ('false_positive', 'False positive'), ('manually_cleared', 'Manually cleared'), ('blocked', 'Blocked for compliance')], db_index=True, default='possible', max_length=32)),
                ('match_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('matched_fields', models.JSONField(blank=True, default=list)),
                ('sponsor_values', models.JSONField(blank=True, default=dict)),
                ('subject_values', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('staff_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions_matches', to='sponsors.sponsorapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sponsor_sanctions_matches', to=settings.AUTH_USER_MODEL)),
                ('source_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_matches', to='sponsors.sanctionssourcesnapshot')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_matches', to='sponsors.sanctionssubject')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['application', 'match_status'], name='sponsors_sp_applica_e8f35c_idx'), models.Index(fields=['source_code', 'match_status'], name='sponsors_sp_source__9320ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('application', 'subject'), name='unique_sponsor_sanctions_match_subject')],
            },
        ),
    ]
