# Generated by Django 5.2.13 on 2026-06-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0014_ring6_weekly_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorapplication',
            name='product_type',
            field=models.CharField(choices=[('annual_ring', 'Annual Ring Sponsorship'), ('weekly_ring', 'Weekly Ring Sponsorship'), ('central_monthly', 'Central Sponsor of the Month')], db_index=True, default='annual_ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='sponsorcell',
            name='product_type',
            field=models.CharField(choices=[('annual_ring', 'Annual Ring Sponsorship'), ('weekly_ring', 'Weekly Ring Sponsorship'), ('central_monthly', 'Central Sponsor of the Month')], db_index=True, default='annual_ring', max_length=32),
        ),
    ]
