# Generated by Django 5.2.13 on 2026-06-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0016_sponsorapplication_contract_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorpayment',
            name='billing_address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
