# Generated by Django 5.2.13 on 2026-09-04 16:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Ny forespørsel'), ('confirmed', 'Bekreftet'), ('completed', 'Fullført'), ('cancelled_customer', 'Kansellert av kunden'), ('cancelled_operator', 'Kansellert av operatøren'), ('no_show', 'Ikke møtt')], default='pending_confirmation', max_length=32)),
                ('pickup_at', models.DateTimeField()),
                ('return_at', models.DateTimeField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('children', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('luggage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('flight_number', models.CharField(blank=True, max_length=24)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NOK', max_length=3)),
                ('fare_snapshot', models.JSONField(default=dict)),
                ('terms_version', models.CharField(max_length=32)),
                ('terms_accepted_at', models.DateTimeField()),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('origin', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('direction', models.CharField(choices=[('to_airport', 'Til Gardermoen'), ('from_airport', 'Fra Gardermoen')], max_length=20)),
                ('estimated_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledo_audit_events', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ledo.booking')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('anonymise_after', models.DateField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_contact', to='ledo.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_class', models.CharField(default='Standard', max_length=80)),
                ('one_way_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='NOK', max_length=3)),
                ('vat_included', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fares', to='ledo.route')),
            ],
            options={
                'ordering': ('route', 'vehicle_class', '-valid_from'),
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='ledo.route'),
        ),
    ]
