# Generated by Django 5.2.13 on 2026-06-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0010_newsfeedentry_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeedentry',
            name='entry_type',
            field=models.CharField(choices=[('recipe_published', 'Recipe Published'), ('article_published', 'Article Published'), ('amuse_bouche_published', 'Pinch Published'), ('amuse_bouche_featured', 'Pinch Featured'), ('site_update', 'Site Update'), ('security_update', 'Security Update'), ('version_release', 'Version Release'), ('admin_note', 'Admin Note'), ('battle_event', 'Chef Battle Event')], db_index=True, max_length=30),
        ),
    ]
