RELEASE_JOURNAL = [
    {
        "version": "version pending backfill",
        "date": "2026-06-09",
        "commit": "1d6294f",
        "title": "Site Audit — Roadmap and Checklist Status",
        "section": "Documentation / Project",
        "summary": "Marked all closed roadmaps and checklists with status headers. Sponsors module confirmed complete. Stripe live switch confirmed closed. Month 1 decisions recorded with mixed status.",
        "checklist": [
            "Marked docs/stripe_sponsors_checklist.md as CLOSED — live switch completed 2026-06-08",
            "Marked docs/sponsor_stripe_live_readiness.md as CLOSED",
            "Marked sponsors/README.md as Complete",
            "Marked docs/month1_decisions.md as MIXED — Content Automation complete, Image Opt / Ads / Affiliates deferred",
            "Marked docs/external_setup_checklist.md as OPEN — Pinterest, Telegram, Instagram/TikTok pending owner action",
        ],
        "stats": [],
        "deployment_status": "deployed",
        "notes": "",
    },
    {
        "version": "version pending backfill",
        "date": "2026-06-09",
        "commit": "c4d7711",
        "title": "Sponsorship Terms Page Redesign + Sponsor of the Month Attribution",
        "section": "Sponsors / Legal / Newsfeed",
        "summary": "Redesigned /sponsors/annual-contract/ to match the legal hub style with anchor navigation, placement cards and full section detail. Added Sponsor of the Month attribution to Telegram messages and newsfeed entries when a central sponsor is active.",
        "checklist": [
            "Redesigned sponsorship terms page: hero, anchor nav, 3 placement cards, 7 legal sections",
            "Removed target=_blank that caused a clipped green-chrome window when opening terms",
            "Added 3-card CSS grid centering fix using :has() selector",
            "Added Sponsor of the Month attribution to Telegram recipe and article messages",
            "Added Sponsored by attribution to newsfeed entry message field",
            "Added Sponsor of the Month attribution clause to sponsorship terms page",
        ],
        "stats": [],
        "deployment_status": "deployed",
        "notes": "When a central sponsor (ring=0, status ACTIVE or SOLD) is active, all new recipe and article publications carry Sponsored by: [name] in Telegram notifications and newsfeed entries.",
    },
    {
        "version": "version pending backfill",
        "date": "2026-06-08",
        "commit": "56f0191",
        "title": "VAT Invoice PDF — Final Layout: Pinned Totals and Meta Balance",
        "section": "Sponsors / PDF / Finance",
        "summary": "Fixed VAT invoice PDF layout: totals, QR code and notes are now pinned to the page bottom via canvas callback. Meta block rebalanced to three rows on each side. ReportLab wrapOn return-value bug fixed.",
        "checklist": [
            "Moved totals, QR block and payment notes to _draw_page canvas callback (pinned to page bottom)",
            "Set b_margin=88mm to prevent flowable content overlapping pinned block",
            "Fixed AttributeError: captured wrapOn return value for table and paragraph heights",
            "Rebalanced meta block: Invoice No / Issue date / Supply date left; Application ref / Payment date / Stripe Ref right",
            "Story now contains only header, rule, meta, parties and items table — no floating totals",
        ],
        "stats": [],
        "deployment_status": "deployed",
        "notes": "Totals, QR code and payment notes are drawn at absolute page coordinates, independent of content length. Invoice fits on a single page.",
    },
    {
        "version": "version pending backfill",
        "date": "2026-06-08",
        "commit": "b2d0c85",
        "title": "VAT Invoice PDF — New Document: Billing Address, generate_invoice_pdf, Dual PDF Email",
        "section": "Sponsors / PDF / Finance",
        "summary": "Added full VAT invoice PDF generation alongside the existing sponsor agreement PDF. Both documents are attached to the sponsor activation email. Added billing_address field to SponsorPayment.",
        "checklist": [
            "Added generate_invoice_pdf() in sponsors/services.py",
            "Added billing_address field to SponsorPayment model (migration 0017)",
            "Attached VAT invoice PDF alongside sponsor agreement PDF in activation email",
            "Invoice includes: Bearcave Limited header, sponsor details, VAT breakdown, QR code, payment reference",
            "Invoice design: single page, Heritage Legal Paper style consistent with agreement PDF",
        ],
        "stats": [
            "Migration 0017: billing_address field on SponsorPayment",
        ],
        "deployment_status": "deployed",
        "notes": "The VAT invoice is generated at activation time. Supply date on the invoice equals the activation date. Suitable for accountant and tax records.",
    },
    {
        "version": "version pending backfill",
        "date": "2026-06-08",
        "commit": "1100961",
        "title": "Sponsor Contract Automation — Agreement Emails, Contract Reference, Resend Action",
        "section": "Sponsors / PDF / Email",
        "summary": "Added automated sponsor agreement PDF generation and email delivery on activation. Added contract reference field, staff resend action and legacy email branding cleanup.",
        "checklist": [
            "Added generate_agreement_pdf() to sponsors/services.py (Heritage Legal Paper style)",
            "Agreement PDF sent to sponsor email on activation",
            "Added contract_reference field to SponsorApplication",
            "Added staff resend-agreement action in sponsor moderation",
            "Removed legacy email branding and outdated weekly sponsor display wording",
            "Fixed sponsor regression test isolation and 7-day checkout expectation",
        ],
        "stats": [
            "Sponsor confirmation email PDF attachment regression: fixed",
        ],
        "deployment_status": "deployed",
        "notes": "Related commit: d3e8212 Remove legacy email branding and weekly sponsor display wording.",
    },
    {
        "version": "2.3.5",
        "date": "2026-06-08",
        "commit": "8dee2be",
        "title": "Weekly Sponsor Ring Pricing, Legal Hub Sync, Privacy Policy Rebuild, Sponsor Puzzle Fixes",
        "section": "Sponsors / Legal / UI",
        "summary": "Added tiered weekly ring pricing (€5–€25/wk). Rebuilt Privacy Policy with legal card system. Synchronised Legal Hub hero with homepage. Fixed sponsor puzzle logo transform propagation and modal close-button overlap. Fixed Open Graph and Twitter meta tags for all section pages.",
        "checklist": [
            "Added weekly sponsor ring (Ring 6) with tiered €5–€25/wk pricing",
            "Updated sponsor puzzle compact ring labels for weekly tier",
            "Rebuilt Privacy Policy using accepted legal card components",
            "Synchronised Legal Hub hero image and overlay with homepage style",
            "Fixed sponsor logo transform not propagating to public puzzle after approval",
            "Fixed sponsor modal close button overlapping form fields on scroll",
            "Fixed Open Graph and Twitter meta tags missing on several section pages",
            "Bumped version to v2.3.5",
        ],
        "stats": [],
        "deployment_status": "deployed",
        "notes": "Ring 6 is a weekly placement (not annual, not auto-renewing). One-off payment for 7 calendar days.",
    },
    {
        "version": "version pending backfill",
        "date": "2026-06-07",
        "commit": "8659459",
        "title": "Sponsors Phase 6 — Stripe Live Readiness Checklist",
        "section": "Sponsors / Stripe / Live Readiness",
        "summary": "Added Stripe live-readiness checklist, safety guards for Stripe mode/key mismatch, webhook secret validation, and documentation for owner/accountant review before real sponsor payments.",
        "checklist": [
            "Added docs/sponsor_stripe_live_readiness.md",
            "Updated docs/stripe_sponsors_checklist.md",
            "Updated Sponsors README with Phase 6 readiness notes",
            "Added safety guards against test/live Stripe key mismatch",
            "Added STRIPE_PRICE_MODE validation",
            "Kept webhook signing secret mandatory for webhook verification",
            "Confirmed no live mode switch was performed",
            "Confirmed no real payments were created",
            "Confirmed sandbox sponsor cleanup completed after smoke testing",
            "Listed unresolved owner/accountant/live-readiness actions",
        ],
        "stats": [
            "Sponsors tests: 139 passed",
            "Legal/newsfeed/recipes tests: 259 passed, 2 skipped",
            "Django check: passed",
            "Migration: not required",
            "Collectstatic: not required",
            "Production health: /sponsors/ HTTP/2 200",
            "Webhook route probe: GET /sponsors/stripe/webhook/ returns HTTP 405, expected POST-only behaviour",
            "Sandbox cleanup: SponsorApplication 0, SponsorPayment 0, SponsorSanctionsMatch 0, SponsorAuditLog 0",
            "Sanctions subjects retained: 6996",
            "Sponsor cells unavailable: 0",
        ],
        "deployment_status": "deployed",
        "notes": "Phase 6 is readiness-only. It records live-readiness documentation and safety guards, not a live Stripe switch. It does not create real payments and does not replace owner/accountant review. Remaining blockers before live payments include Stripe account activation confirmation, VAT/Stripe Tax review, production email delivery confirmation, live webhook setup/signing secret, database backup and explicit project owner authorisation.",
    },
    {
        "version": "2.3.4",
        "date": "2026-06-06",
        "commit": "9ac1665",
        "title": "Author Dashboard Filter Navigation",
        "section": "Author Dashboard / Recipes",
        "summary": "Simplified and unified category filter navigation across the author dashboard and recipe mood sections.",
        "checklist": [
            "Simplified dashboard filter navigation",
            "Replaced standalone filter buttons with category navigation links",
            "Unified recipe mood categories with category navigation",
            "Aligned dashboard filter buttons with the site button design system",
        ],
        "stats": [],
        "deployment_status": "deployed",
        "notes": "",
    },
    {
        "version": "version pending backfill",
        "date": "2026-06-06",
        "commit": "fb1800e",
        "title": "Sponsors Compliance Phase 1 - Stripe Purchase and Manual Compliance Review",
        "section": "Sponsors / Stripe / Compliance",
        "summary": "Added sponsor declaration before Stripe, paid_pending_compliance_review, manual compliance clear before approval, admin attention badges and the full sponsor approval flow.",
        "checklist": [
            "Added mandatory sponsor declaration checkboxes before Stripe",
            "Moved paid sponsor applications to paid_pending_compliance_review",
            "Required staff manual compliance clear before approve and publish",
            "Added sponsor moderation attention badges",
            "Confirmed annual sponsor sandbox purchase flow",
            "Confirmed Stripe test payment flow",
            "Confirmed Telegram announcement sends only after Approve and publish",
            "Confirmed sponsor becomes active after staff approval",
        ],
        "stats": [
            "Manual smoke test Phase 1: passed",
            "Sandbox annual sponsor purchase: passed",
            "Stripe test payment: passed",
            "Admin badge after payment: passed",
            "Telegram after approval only: passed",
            "Production health: /sponsors/ HTTP/2 200",
        ],
        "deployment_status": "deployed",
        "notes": "Related commit: 4ab2936 Add sponsor moderation attention badges. This is an internal staff release ledger entry based on project owner smoke-test notes and production deployment records.",
    },
    {
        "version": "version pending backfill",
        "date": "2026-06-06",
        "commit": "1f5eb89",
        "title": "Sponsors Compliance Phase 2 - Official Sanctions Source Ingestion",
        "section": "Sponsors / Compliance",
        "summary": "Added official EU/UN sanctions source ingestion, source snapshots, source subject storage, RSS-based EU source discovery, UN source loading and staff source status visibility.",
        "checklist": [
            "Added SanctionsSourceSnapshot and SanctionsSubject data foundation",
            "Added update_sanctions_sources management command",
            "Added official EU FSF RSS discovery",
            "Added tokenized EU XML v1.1 download through official RSS",
            "Added CSV fallback and manual EU file import fallback",
            "Kept --allow-partial update behaviour",
            "Preserved failed snapshots for audit",
            "Kept Phase 3 matching deliberately out of scope",
        ],
        "stats": [
            "EU sanctions source: success, 5994 records",
            "UN sanctions source: skipped_not_modified, 1002 records",
            "Total sanctions subjects: 6996",
            "Django check: passed",
            "Production health: /sponsors/ HTTP/2 200",
        ],
        "deployment_status": "deployed",
        "notes": "Related commits: 8fc01bb Add official sanctions source ingestion; 65062d6 Fix EU sanctions source download fallback; cd44a19 Add manual EU sanctions file import. Phase 2 imports and tracks official sources only. Sponsor matching and possible-match workflow are Phase 3.",
    },
    {
        "version": "version pending backfill",
        "date": "2026-06-07",
        "commit": "628f3f4",
        "title": "Sponsors Compliance Phase 5 - Legal and UI Polish",
        "section": "Sponsors / Compliance / Staff UI",
        "summary": "Polished applicant-facing sponsor wording, staff compliance/refund messages, notification clarity and internal sponsor compliance documentation.",
        "checklist": [
            "Clarified that payment reserves a sponsor spot but does not guarantee approval, publication or activation",
            "Clarified pending compliance review wording on checkout success and sponsor application UI",
            "Clarified manual refund tracking and refund completion wording",
            "Updated sponsor moderation list and detail helper text for staff action queues",
            "Confirmed public pages do not expose sanctions match details, source URLs, staff notes, audit logs or Stripe identifiers",
        ],
        "stats": [
            "Test results pending final Phase 5 run",
        ],
        "deployment_status": "pending deployment",
        "notes": "Phase 5 is wording, UI clarity and documentation only. It does not change Stripe payment/webhook semantics, Telegram trigger behaviour, sanctions source ingestion or sanctions matching logic.",
    },
]
