# Generated by Django 5.2.8 on 2025-11-27 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя / псевдоним')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug для URL')),
                ('bio', models.TextField(blank=True, verbose_name='Кратко об авторе')),
            ],
            options={
                'verbose_name': 'Автор рецепта',
                'verbose_name_plural': 'Авторы рецептов',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('prep_time_minutes', models.PositiveSmallIntegerField(default=0)),
                ('cook_time_minutes', models.PositiveSmallIntegerField(default=0)),
                ('servings', models.PositiveSmallIntegerField(default=1)),
                ('difficulty',
                 models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy',
                                  max_length=10)),
                ('category', models.CharField(
                    choices=[('irish_classic', 'Irish classic'), ('home_cooking', 'Home cooking'),
                             ('restaurant_style', 'Restaurant-style at home'), ('vintage', 'Vintage / Old cookbooks'),
                             ('modern', 'Modern & experimental')], default='home_cooking', max_length=32)),
                ('ingredients', models.TextField(help_text='One ingredient per line.')),
                ('method', models.TextField(help_text='Step-by-step method.')),
                ('tips', models.TextField(blank=True)),
                ('irish_context', models.TextField(blank=True)),
                ('allergens', models.TextField(blank=True)),
                ('source_type', models.CharField(
                    choices=[('original', 'Original'), ('family', 'Family recipe'), ('cookbook', 'Cookbook'),
                             ('website', 'Website'), ('restaurant', 'Restaurant'), ('other', 'Other')],
                    default='original', max_length=20)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('source_author', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('source_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='recipes', to='recipes.recipeauthor', verbose_name='Автор')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='recipes_rec_slug_412256_idx'),
                            models.Index(fields=['category'], name='recipes_rec_categor_081389_idx')],
            },
        ),
    ]
