# Generated by Django 5.2.13 on 2026-04-29 13:45

from django.db import migrations, models

import recipes.models
import recipes.validators


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0010_recipeauthor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.recipe_cover_upload_to,
                                    validators=[recipes.validators.ImageUploadValidator()],
                                    verbose_name='Preview image'),
        ),
        migrations.AlterField(
            model_name='recipeauthor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.author_avatar_upload_to,
                                    validators=[recipes.validators.ImageUploadValidator()]),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to=recipes.models.recipe_gallery_upload_to,
                                    validators=[recipes.validators.ImageUploadValidator()]),
        ),
    ]
