# Generated by Django 5.2.13 on 2026-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_profanityword'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='ip_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
