# Generated by Django 5.2.8 on 2026-04-10

import uuid

from django.db import migrations, models

import recipes.models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="media_uid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=recipes.models.recipe_cover_upload_to,
                verbose_name="Preview image",
            ),
        ),
        migrations.CreateModel(
            name="RecipeImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to=recipes.models.recipe_gallery_upload_to)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe gallery image",
                "verbose_name_plural": "Recipe gallery images",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
