# Generated by Django 5.2.8 on 2026-04-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_recipe_media_uid_alter_recipe_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='media_uid',
        ),
        migrations.AddField(
            model_name='recipe',
            name='media_folder',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
