# Generated by Django 5.2.8 on 2026-04-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0004_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeauthor',
            options={'verbose_name': 'Recipe author', 'verbose_name_plural': 'Recipe authors'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='recipes', to='recipes.recipeauthor', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='recipeauthor',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Short author bio'),
        ),
        migrations.AlterField(
            model_name='recipeauthor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name / pen name'),
        ),
        migrations.AlterField(
            model_name='recipeauthor',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL slug'),
        ),
    ]
