# Generated by Django 5.2.8 on 2026-04-13 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0006_merge_20260411_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Optional calories per serving.', null=True),
        ),
        migrations.CreateModel(
            name='RecipeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                             to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Recipe comment',
                'verbose_name_plural': 'Recipe comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings',
                                             to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Recipe rating',
                'verbose_name_plural': 'Recipe ratings',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gte', 1), ('value__lte', 5)),
                                                       name='recipe_rating_value_between_1_and_5')],
            },
        ),
    ]
