# Generated by Django 5.2.13 on 2026-04-29 22:43

import django.db.models.deletion
from django.db import migrations, models


def assign_heritage_recipes(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")
    RecipeAdditionalCategory = apps.get_model("recipes", "RecipeAdditionalCategory")

    heritage_titles = [
        "Farmhouse Farls",
        "Classic Irish Boxty",
        "Cottage Pie",
        "Irish Stew",
    ]

    for recipe in Recipe.objects.filter(title__in=heritage_titles):
        RecipeAdditionalCategory.objects.get_or_create(
            recipe=recipe,
            category="everyday_irish_cooking",
        )
        recipe.category = "irish_culinary_heritage"
        recipe.save(update_fields=["category"])


def unassign_heritage_recipes(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")
    RecipeAdditionalCategory = apps.get_model("recipes", "RecipeAdditionalCategory")

    heritage_titles = [
        "Farmhouse Farls",
        "Classic Irish Boxty",
        "Cottage Pie",
        "Irish Stew",
    ]

    for recipe in Recipe.objects.filter(title__in=heritage_titles):
        RecipeAdditionalCategory.objects.filter(
            recipe=recipe,
            category="everyday_irish_cooking",
        ).delete()
        recipe.category = "everyday_irish_cooking"
        recipe.save(update_fields=["category"])


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0011_alter_recipe_hero_image_alter_recipeauthor_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeAdditionalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(
                    choices=[('breakfast_and_brunch', 'Breakfast and Brunch'), ('lunch', 'Lunch'), ('dinner', 'Dinner'),
                             ('light_bites_and_appetisers', 'Light Bites and Appetisers'), ('desserts', 'Desserts'),
                             ('drinks', 'Drinks'), ('main_courses', 'Main Courses'), ('side_dishes', 'Side Dishes'),
                             ('soups_and_stews', 'Soups and Stews'), ('salads', 'Salads'),
                             ('pasta_and_noodles', 'Pasta and Noodles'), ('bread_and_baking', 'Bread and Baking'),
                             ('grilling_and_barbecue', 'Grilling and Barbecue'),
                             ('meat_and_poultry', 'Meat and Poultry'), ('fish_and_seafood', 'Fish and Seafood'),
                             ('vegetables', 'Vegetables'), ('fruit', 'Fruit'), ('irish_cuisine', 'Irish Cuisine'),
                             ('irish_culinary_heritage', 'Irish Culinary Heritage'),
                             ('traditional_irish_dishes', 'Traditional Irish Dishes'),
                             ('modern_irish_cooking', 'Modern Irish Cooking'),
                             ('everyday_irish_cooking', 'Everyday Irish Cooking'),
                             ('seasonal_and_festive_irish', 'Seasonal and Festive (Irish)'),
                             ('healthy_eating', 'Healthy Eating'), ('ingredients', 'Ingredients'),
                             ('irish_producers_and_brands', 'Irish Producers and Brands')], max_length=64)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='additional_category_links', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Additional recipe category',
                'verbose_name_plural': 'Additional recipe categories',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'category'),
                                                        name='recipes_additional_category_unique_per_recipe')],
            },
        ),
        migrations.RunPython(assign_heritage_recipes, unassign_heritage_recipes),
    ]
