# Generated by Django 5.2.13 on 2026-05-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_recipe_moderation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='hero_image_alt_text',
            field=models.CharField(blank=True, help_text='Describe the recipe image for accessibility and search indexing.', max_length=255, verbose_name='Recipe image alt text'),
        ),
    ]
