# Generated by Django 5.2.13 on 2026-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_recipe_source_note_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source_type',
            field=models.CharField(choices=[('original', 'Original'), ('ai_assisted', 'AI assisted'), ('family', 'Family recipe'), ('cookbook', 'Cookbook'), ('website', 'Website'), ('restaurant', 'Restaurant'), ('other', 'Other')], default='original', max_length=20),
        ),
    ]
