# Generated by Django 5.2.13 on 2026-05-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0033_recipe_generation_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('bread_and_baking', 'Bread and Baking'), ('soups_and_stews', 'Soups and Stews'), ('fish_and_seafood', 'Fish and Seafood'), ('vegetables', 'Vegetables'), ('meat_and_poultry', 'Meat and Poultry'), ('desserts', 'Desserts'), ('drinks', 'Drinks'), ('breakfast_and_brunch', 'Breakfast and Brunch'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('light_bites_and_appetisers', 'Light Bites and Appetisers'), ('main_courses', 'Main Courses'), ('side_dishes', 'Side Dishes'), ('salads', 'Salads'), ('pasta_and_noodles', 'Pasta and Noodles'), ('grilling_and_barbecue', 'Grilling and Barbecue'), ('fruit', 'Fruit'), ('irish_cuisine', 'Irish Cuisine'), ('irish_culinary_heritage', 'Irish Culinary Heritage'), ('traditional_irish_dishes', 'Traditional Irish Dishes'), ('modern_irish_cooking', 'Modern Irish Cooking'), ('everyday_irish_cooking', 'Everyday Irish Cooking'), ('seasonal_and_festive_irish', 'Seasonal and Festive (Irish)'), ('healthy_eating', 'Healthy Eating'), ('ingredients', 'Ingredients'), ('irish_producers_and_brands', 'Irish Producers and Brands')], default='everyday_irish_cooking', max_length=64),
        ),
        migrations.AlterField(
            model_name='recipeadditionalcategory',
            name='category',
            field=models.CharField(choices=[('bread_and_baking', 'Bread and Baking'), ('soups_and_stews', 'Soups and Stews'), ('fish_and_seafood', 'Fish and Seafood'), ('vegetables', 'Vegetables'), ('meat_and_poultry', 'Meat and Poultry'), ('desserts', 'Desserts'), ('drinks', 'Drinks'), ('breakfast_and_brunch', 'Breakfast and Brunch'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('light_bites_and_appetisers', 'Light Bites and Appetisers'), ('main_courses', 'Main Courses'), ('side_dishes', 'Side Dishes'), ('salads', 'Salads'), ('pasta_and_noodles', 'Pasta and Noodles'), ('grilling_and_barbecue', 'Grilling and Barbecue'), ('fruit', 'Fruit'), ('irish_cuisine', 'Irish Cuisine'), ('irish_culinary_heritage', 'Irish Culinary Heritage'), ('traditional_irish_dishes', 'Traditional Irish Dishes'), ('modern_irish_cooking', 'Modern Irish Cooking'), ('everyday_irish_cooking', 'Everyday Irish Cooking'), ('seasonal_and_festive_irish', 'Seasonal and Festive (Irish)'), ('healthy_eating', 'Healthy Eating'), ('ingredients', 'Ingredients'), ('irish_producers_and_brands', 'Irish Producers and Brands')], max_length=64),
        ),
    ]
