# Generated by Django 5.2.13 on 2026-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0037_crestedten_full_irish'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeauthor',
            name='has_arena_console_access',
            field=models.BooleanField(default=False, help_text='Grants read access to the Chef Battles Arena Master Console. Requires a superuser account as well. Only the site owner can grant or revoke this.', verbose_name='Can open the Arena Master Console'),
        ),
    ]
