# Generated by Django 5.2.13 on 2026-07-28 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0038_recipeauthor_has_arena_console_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeauthor',
            name='name',
            field=models.CharField(help_text='Public chef alias — max 14 characters (fits the arena crown pad).', max_length=100, validators=[django.core.validators.MaxLengthValidator(14)], verbose_name='Name / pen name'),
        ),
    ]
