# Generated by Django 5.2.13 on 2026-08-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0039_alter_recipeauthor_name_pen_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeauthor',
            name='gallery_avatar',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Chosen gallery portrait'),
        ),
    ]
